project:
  type: website

website:
  title: "Imran's Postgrad repo"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    tools:
      - icon: house-heart
        href: about.qmd      
      - icon: github
        href: "https://github.com/imranmi/imran-s-data-sc"
      - icon: linkedin
        href: "https://www.linkedin.com/in/imran-ibrahim-116a236b"
    search: true
    
  
    left:
      - text: Exercises in R
        menu: 
          - text: R Exercise 1 - Analysing PISA's education survey data
            href: R-ex/R-Ex1/R_Ex1.html
          - text: R Exercise 2 - 5 Exploratory Data Analyses on Pisa Data
            href: R-ex/R-Ex2/R_Ex2.html
          - text: R Exercise 3 - DataVis Makeover of another student's work
            href: R-ex/R-Ex3/R_Ex3.html
          - text: R Exercise 4 - Be Weatherwise or Otherwise
            href: R-ex/R-Ex4/R_Ex4.html
          - text: R Exercise 5 - Visual Analytics exercise on Armed conflicts - Initial Draft
            href: R-ex/R-Ex5/R_Ex5.html
          - text: R Exercise 6 - Geospatial Analysis1 - Local Measures of Spatial Autocorrelation
            href: R-ex/R-Ex6/R_Ex6.html
          - text: R Exercise 7 - Geospatial Analysis2 - Emerging Hot Spot Analysis
            href: R-ex/R-Ex7/R_Ex7.html
          - text: R Exercise 8 - Geospatial Analysis3 - Spatially Constrained Clustering-ClustGeo method
            href: R-ex/R-Ex8/R_Ex8.html
          - text: Group Project Poster - Decoding Chaos - Analysing Armed conflicts in Myammar
            href: R-ex/R-Ex9/R_Ex9.html  
      - text: Exercises in Python
        menu: 
          - text: Python Exercise 1 - Automate the design of a 3-stocks portfolio for a given target return 
            href: Python-ex/Python-Ex1/Python_Ex1.html
          - text: Python Exercise 2 - Designing a 3-stock portfolio for a robo-advisor 
            href: Python-ex/Python-Ex2/Python_Ex2.html
          - text: Python Exercise 3 - Project - Predicting Stock Prices through Time series Analysis 
            href: Python-ex/Python-Ex3/Python_Ex3.html
      - text: SAS Viya Exercises
        menu: 
          - text: Assignment 1 - Show me the numbers 
            href: Write-ex/Write-Ex1/Write_Ex1.html
          - text: Assignment 2 - Be Customer wise or otherwise 
            href: Write-ex/Write-Ex2/Write_Ex2.html
          - text: Project - Loan Default prediction    
            href: Write-ex/Write-Ex3/Write_Ex3.html
          - text: Project Poster - Loan Default prediction    
            href: Write-ex/Write-Ex4/Write_Ex4.html
      - text: Written Assignments (Fintech) 
        menu: 
          - text: Assignment 1 - Factors that contributed to the rise of Fintech companies 
            href: Article-ex/Article-Ex1/Article_Ex1.html
          - text: Assignment 2 - Banks have changed the way they deploy technology
            href: Article-ex/Article-Ex2/Article_Ex2.html
          - text: Assignment 3  
            href: Article-ex/Article-Ex3/Article_Ex3.html
          - text: Assignment 4   
            href: Article-ex/Article-Ex4/Article_Ex4.html        
          - text: Assignment 5 
            href: Article-ex/Article-Ex5/Article_Ex5.html
          - text: Assignment 6 
            href: Article-ex/Article-Ex6/Article_Ex6.html
          - text: Assignment 7  
            href: Article-ex/Article-Ex7/Article_Ex7.html
          - text: Assignment 8   
            href: Article-ex/Article-Ex8/Article_Ex8.html  
format:
  html:
    theme: 
      - cerulean
      - theme.scss
    mermaid: 
      theme: neutral
    css: styles.css
    toc: true
    grid:
      sidebar-width: 100px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 2.0rem
editor: visual