project:
  type: website

website:
  title: "Imran's Data Science website"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    tools:
      - icon: house-heart
        href: about.qmd      
      - icon: github
        href: "https://github.com/imranmi/imran-s-data-sc"
      - icon: linkedin
        href: "https://www.linkedin.com/in/imran-ibrahim-116a236b"
    search: true
    
  
    left:
      - text: Exercises in R
        menu: 
          - text: R Exercise 1 - Analysing PISA's education survey data
            href: R-ex/R-Ex1/R_Ex1.html
          - text: R Exercise 2 - 5 Exploratory Data Analyses on Pisa Data
            href: R-ex/R-Ex2/R_Ex2.html
          - text: R Exercise 3 - DataVis Makeover of another student's work
            href: R-ex/R-Ex3/R_Ex3.html
          - text: R Exercise 4 - Be Weatherwise or Otherwise
            href: R-ex/R-Ex4/R_Ex4.html
          - text: R Exercise 5 - Visual Analytics exercise on Armed conflicts - Initial Draft
            href: R-ex/R-Ex5/R_Ex5.html
          - text: R Exercise 6 - Geospatial Analysis1 - Local Measures of Spatial Autocorrelation
            href: R-ex/R-Ex6/R_Ex6.html
          - text: R Exercise 7 - Geospatial Analysis2 - Emerging Hot Spot Analysis
            href: R-ex/R-Ex7/R_Ex7.html
          - text: R Exercise 8 - Geospatial Analysis3 - Spatially Constrained Clustering-ClustGeo method
            href: R-ex/R-Ex8/R_Ex8.html   
      - text: Exercises in Python
        menu: 
          - text: Python Exercise 1 
            href: Python-ex/Python-Ex1/Python_Ex1.html
          - text: Python Exercise 2 
            href: Python-ex/Python-Ex1/Python_Ex1.html
          - text: Python Exercise 3 
            href: Python-ex/Python-Ex1/Python_Ex1.html
      - text: Write-ups
        menu: 
          - text: Write-up 1 
            href: Write-ex/Write-Ex1/Write_Ex1.html
          - text: Write-up 2 
            href: Write-ex/Write-Ex2/Write_Ex2.html
          - text: Write-up 3 
            href: Write-ex/Write-Ex3/Write_Ex3.html     
          
format:
  html:
    theme: 
      - cerulean
      - theme.scss
    mermaid: 
      theme: neutral
    css: styles.css
    toc: true
    grid:
      sidebar-width: 100px
      body-width: 1200px
      margin-width: 200px
      gutter-width: 2.0rem
editor: visual