{
  "hash": "120c277fb6bdd2039fe94b26143756f1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-Home Exercise 1c : DataVis Makeover of another student's work\"\nauthor: \"Imran Ibrahim\"\ndate: August 4, 2024\ndate-modified: \"last-modified\"\ntoc: true\nexecute: \n  eval: true\n  echo: true\n  freeze: true\n  warning: false\n  message: false\nbibliography: references.bib\n---\n\n\n::: callout-important\n## DataVis Makeover\n\nRemaking a peer’s original design by improving the clarity and aesthetics of charts by creating an alternative design.\n:::\n\n# 1. The Task\n\nIn this take-home exercise, we are required to:\n\n-   select one of the Take-home Exercise 1 prepared by our classmates,\n\n-   critique the submission in terms of clarity and aesthetics,\n\n-   prepare a sketch for the alternative design by using the data visualization design principles and best practices we have learned in Lesson 1 and 2, and\n\n-   remake the original design by using ggplot2, ggplot2 extensions and tidyverse packages.\n\n# 2. Data Preparation\n\nI will follow the data preparation steps done by the original author of the selector graphs. The steps are listed below for easy reference. As this is not the focus of the exercise, I will not go into the minute details of preparation.\n\n## 2.1 Loading R packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, haven, ggrepel, ggthemes, hrbrthemes, patchwork, intsvy, ggdist, ggridges,colorspace, plotly)\n```\n:::\n\n\n## 2.2 Importing the Data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstu_qqq_SG <- \n  read_rds(\"data/stu_qqq_SG.rds\")\n```\n:::\n\n\n## 2.3 Removing missing values and Converting data types\n\nRows with missing values for ESCS were removed before further analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstu_qqq_SG_clean <- stu_qqq_SG[complete.cases(stu_qqq_SG[, \"ESCS\"]), ]\n```\n:::\n\n\nCNTSCHID and CNTSTUID's data types were changed to character.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstu_qqq_SG_clean$CNTSCHID <- as.character(stu_qqq_SG_clean$CNTSCHID)\nstu_qqq_SG_clean$CNTSTUID <- as.character(stu_qqq_SG_clean$CNTSTUID)\n```\n:::\n\n\n## 2.4 Binning Variable ESCS\n\nThe ESCS variable was binned into quantiles using the [mutate()](https://dplyr.tidyverse.org/reference/mutate.html) and [cut()](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/cut) function\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstu_qqq_SG_clean <- stu_qqq_SG_clean %>%\n  mutate(ESCS_recoded = cut(ESCS,breaks=quantile(ESCS,c(0,0.25,0.5,0.75,1)),labels=c(\"Very Low\",\"Low\",\"Medium\",\"High\"),include.lowest=TRUE))\n```\n:::\n\n\n## 2.5 Recoding ST004D01T (Gender) variable\n\nVariable ST004D01T, was recoded to labels to “Female” and “Male” respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstu_qqq_SG_clean$ST004D01T <- recode(stu_qqq_SG_clean$ST004D01T, \"1\" = \"Female\", \"2\" = \"Male\")\n```\n:::\n\n\n# 3. Visualization Critique and Remake\n\nThe graphs created by the author will be evaluated and improvements in terms of clarity and aesthetics will be applied in the makeover.\n\n## 3.1 General distribution of students’ performance in Math, Science and Reading\n\nFirst, the author had created a data folder path to save any data files generated:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ndata_folder_path <- file.path(getwd(), \"data\")\n```\n:::\n\n\nThe code below uses the `instvy package` to extract the composite Means and Standard Deviations of PV values across the population of students that took the assessment.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npvmathgeneral <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"MATH\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvmath_general\",folder=data_folder_path)\n\npvmathgeneral$subject <- \"Math\"\n\npvreadgeneral <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"READ\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvread_general\",folder=data_folder_path)\n\npvreadgeneral$subject <- \"Reading\"\n\npvsciegeneral <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"SCIE\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvscie_general\",folder=data_folder_path)\n\npvsciegeneral$subject <- \"Science\"\n\nmergedgeneral <- rbind(pvmathgeneral,pvreadgeneral,pvsciegeneral)\nmergedgeneral %>% relocate(subject)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  subject Freq   Mean s.e.     SD  s.e\n1    Math 6559 575.27 1.26 102.68 0.93\n2 Reading 6559 543.25 1.91 105.73 1.16\n3 Science 6559 561.97 1.33  99.02 1.10\n```\n\n\n:::\n:::\n\n\nA plot to show the general distribution of Math, Reading and Science scores was generated using the code below.\n\n::: panel-tabset\n## The original plot\n\n![](images/clipboard-3818993272.png)\n\nThe author had created a series of error bars across the 3 subjects to represent the distribution of Student scores across the 3 subjects.\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1<- ggplot(mergedgeneral, aes(x = subject, y = Mean,colour=subject)) +\n  geom_boxplot(width = 0.5, position = position_dodge(width = 0.75),lwd=0.5,show.legend=FALSE) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    shape = 18,\n    size = 5,\n    aes(colour=subject),\n    position = position_dodge(width = 0.75)) +\n  geom_errorbar(\n    aes(ymin = Mean - SD, ymax = Mean + SD),\n    width = 0.5,\n    size=0.8,\n    position = position_dodge(width = 0.5)\n  ) +\n  labs(title = \"Scores across Math, Reading and Science across all 15-year olds who took PISA 2022 in SGP\") +\n  ylab(\"Scores\") +\n  xlab(\"Subject\")+\n  scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 50))+\n  coord_flip() +\n  theme_minimal(base_size = 12)\np1\n```\n:::\n\n:::\n\n### 3.1.1 Evaluation\n\n+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Assessment Criteria | Critique/Feedback                                                                                                                                                                                                  | Possible Improvements                                                                                                                                                                                                                                                                     |\n+=====================+====================================================================================================================================================================================================================+===========================================================================================================================================================================================================================================================================================+\n| **Clarity**         | 1.  Although the original plot enables me to visualize the differences in scores across subjects, I am unclear as to which score this is showing. Is it PV1 or average of the PV values?                           | 1.  The code and subset used is not suitable to plot a **Distribution** of student scores across subjects. I will extract a new subset with all PV1 scores at the individual student level. This will then be used to plot the distribution of student scores for the different subjects. |\n|                     |                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                           |\n|                     | 2.  Graph is titled as “Scores across Math, Reading and Science”, however the code indicates that mean scores +/- one standard deviation were generated instead.                                                   |                                                                                                                                                                                                                                                                                           |\n|                     |                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                           |\n|                     | 3.  The data subset used for this plot only has 3 observations and 6 variables. Upon inspecting the data set, it is actually the composite mean score for each subject for the entire student cohort.              |                                                                                                                                                                                                                                                                                           |\n+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Aesthetics**      | 1.  There is already a legend on the right which identifies subjects by colour, thus making the Y axis labels seem redundant.                                                                                      | 1.  To remove the legend or Y-Axis labels, to reduce non-data ink.                                                                                                                                                                                                                        |\n|                     |                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                           |\n|                     | 2.  The scale for the X-axis is from 0 to 1000, in increments of 50. Because of the \"shortness\" of the error bars, the graph appears too elongated. This contributes to \"extra\" space and additional non-data ink. | 2.  Shorten the X-axis, or extract new data points to populate the correct range of scores.                                                                                                                                                                                               |\n|                     |                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                           |\n|                     | 3.  Unable to decipher the actual scores even with the X-axis tick marks.                                                                                                                                          | 3.  To annotate the mean scores onto the plot, so that we can remove the background grid lines and X-axis tick marks and reduce non-data ink.                                                                                                                                             |\n|                     |                                                                                                                                                                                                                    |                                                                                                                                                                                                                                                                                           |\n|                     | 4.  Since the subjects are clearly labelled in the Y axis, the label “Subject” can be removed, to minimize non-data ink.                                                                                           | 4.  To remove the label \"Subject\", since it does not provide additional information to readers.                                                                                                                                                                                           |\n+---------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n::: callout-note\n## Observation\n\nUpon closer examination of the code used, the author had included an error bar with Mean +/- one standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#geom_errorbar(\n    #aes(ymin = Mean - SD, ymax = Mean + SD),\n    #width = 0.5,\n    #size=0.8,\n    #position = position_dodge(width = 0.5)\n```\n:::\n\n\nI would conclude that this plot is actually comparing the mean subject scores across subjects.\n:::\n\nExamining the subset used for the original plot in more detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(mergedgeneral)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Freq   Mean s.e.     SD  s.e subject\n1 6559 575.27 1.26 102.68 0.93    Math\n2 6559 543.25 1.91 105.73 1.16 Reading\n3 6559 561.97 1.33  99.02 1.10 Science\n```\n\n\n:::\n:::\n\n\nThe *mergedgeneral* subset table only has 3 observations and 6 variables.\n\n::: callout-note\n## Conclusion\n\nThe code and data subset used by the author will not be able to plot a **Distribution** of student scores across subjects.\n\nI will revert to the original large data set to extract PV1 scores which are available for all students to create new plots to visualize the distribution of scores.\n:::\n\n### 3.1.2 Sketch of Proposed Design\n\nRough sketch of proposed design is shown below.\n\n![](images/clipboard-3845138551.png)\n\n### 3.1.3 Remake\n\nThe original data sub set and plot is unable to exhibit the distribution of student scores across subjects, due to the lack of scores at an individual student level.\n\nFirst, I will use the code below derive some reference lines (mean and median) for our histograms.\n\nTo populate the distribution of scores for the student cohort, I will use PV1 scores, which are available for all students.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmean_pv1math <- mean(stu_qqq_SG$PV1MATH)\nmedian_pv1math <- median(stu_qqq_SG$PV1MATH)\nmean_pv1read <- mean(stu_qqq_SG$PV1READ)\nmedian_pv1read <- median(stu_qqq_SG$PV1READ)\nmean_pv1scie <- mean(stu_qqq_SG$PV1SCIE)\nmedian_pv1scie <- median(stu_qqq_SG$PV1SCIE)\n```\n:::\n\n\nNext, I will use the code below and extract data points (PV1 scores) from the original large data set to create Histograms with Density plots for each subject.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\np_1 <- ggplot(stu_qqq_SG, aes(x = PV1MATH)) +\n  geom_histogram(aes(y = ..density..), binwidth = 20, color = \"black\", fill='lightblue') +\n  geom_density(color = \"purple\") + \n  coord_cartesian(xlim = c(0, 1000)) +\n  labs(x = \"Math Scores\", y = \"Density\") + # Change label to 'Density'\n  geom_vline(xintercept = mean_pv1math, color = 'black', size = 0.65, linetype = \"dashed\") +\n  geom_text(\n    aes(x = mean_pv1math, y = 0.0025, label = paste(\"Mean:\", round(mean_pv1math, 2))), # Adjust y position for text\n    color = \"black\", hjust = 1.75, size = 3\n  ) +\n  geom_vline(xintercept = median_pv1math, color = 'red', size = 0.65, linetype = \"dashed\") +\n  geom_text(\n    aes(x = median_pv1math, y = 0.0025, label = paste(\"Median:\", round(median_pv1math, 2))), # Adjust y position for text\n    color = \"red\", hjust = -0.75, size = 3\n  ) +\n  theme_minimal()\n\np_2 <- ggplot(stu_qqq_SG, aes(x = PV1READ)) +\n  geom_histogram(aes(y = ..density..), binwidth = 20, color = \"black\", fill='lightgreen') +\n  geom_density(color = \"purple\") + \n  coord_cartesian(xlim = c(0, 1000)) +\n  labs(x = \"Reading Scores\", y = \"Density\") + \n  geom_vline(xintercept = mean_pv1read, color = 'black', size = 0.65, linetype = \"dashed\") +\n  geom_text(\n    aes(x = mean_pv1read, y = 0.0025, label = paste(\"Mean:\", round(mean_pv1read, 2))), # Adjust y position for text\n    color = \"black\", hjust = 1.75, size = 3\n  ) +\n  geom_vline(xintercept = median_pv1read, color = 'red', size = 0.65, linetype = \"dashed\") +\n  geom_text(\n    aes(x = median_pv1read, y = 0.0025, label = paste(\"Median:\", round(median_pv1read, 2))), # Adjust y position for text\n    color = \"red\", hjust = -0.75, size = 3\n  ) +\n  theme_minimal()\n\np_3 <- ggplot(stu_qqq_SG, aes(x = PV1SCIE)) +\n  geom_histogram(aes(y = ..density..), binwidth = 20, color = \"black\", fill='lightpink') +\n  geom_density(color = \"purple\") +  \n  coord_cartesian(xlim = c(0, 1000)) +\n  labs(x = \"Science Scores\", y = \"Density\") + \n  geom_vline(xintercept = mean_pv1scie, color = 'black', size = 0.65, linetype = \"dashed\") +\n  geom_text(\n    aes(x = mean_pv1scie, y = 0.0025, label = paste(\"Mean:\", round(mean_pv1scie, 2))), # Adjust y position for text\n    color = \"black\", hjust = 1.75, size = 3\n  ) +\n  geom_vline(xintercept = median_pv1scie, color = 'red', size = 0.65, linetype = \"dashed\") +\n  geom_text(\n    aes(x = median_pv1scie, y = 0.0025, label = paste(\"Median:\", round(median_pv1scie, 2))), # Adjust y position for text\n    color = \"red\", hjust = -0.75, size = 3\n  ) +\n  theme_minimal()\n\np_4 <- ggplot(stu_qqq_SG, aes(x = PV1MATH, fill = \"Math\")) +\n  geom_density(alpha = 0.5) +\n  geom_density(data = stu_qqq_SG, aes(x = PV1READ, fill = \"Reading\"), alpha = 0.5) +\n  geom_density(data = stu_qqq_SG, aes(x = PV1SCIE, fill = \"Science\"), alpha = 0.5) +\n  labs(x = \"Combined Scores\",\n       y = \"Density\") +\n  scale_fill_manual(values = c(\"Math\" = \"lightblue\", \"Reading\" = \"lightgreen\", \"Science\" = \"lightpink\")) +\n  guides(fill = FALSE) +  # Remove the legend\n  theme_minimal()\n```\n:::\n\n\nFinally, using the code below, I will create a composite graph for all the histograms and density plots.\n\n\n::: {.cell .column-body-outset-right}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npatch1 <- (p_1 + p_2) / (p_3 + p_4)  + \n              plot_annotation(\n                title = \"Distribution of student performance in Math, Reading and Science\",\n                subtitle = \"All subjects exhibit a slight left-skewed distribution\" )\n\npatch1 & theme( axis.text.y = element_blank(),panel.grid.major = element_blank(),)\n```\n\n::: {.cell-output-display}\n![](R_Ex3_files/figure-html/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n::: callout-tip\n## Revised Plot\n\nThe revised plot consists of a patchwork of 3 histograms with density curves, and a combined density curve overlay for the 3 subjects.\\\n\\\nReference lines for the mean and median scores are added to enable readers to infer the skewness of the distribution of student scores.\\\n\\\nThe revised plot will enable readers to quickly infer the nature of the distributions of the subject scores for the student cohort.\n:::\n\n## 3.2 Distribution of students’ performance in Math, Science and Reading across schools\n\nThe author has used the [`pisa.mean.pv`](https://www.rdocumentation.org/packages/intsvy/versions/2.8/topics/pisa.mean.pv) function from [`intsvy`](https://daniel-caro.com/r-intsvy)`package`, to obtain the composite Mean and Standard Deviation values from “PV1MATH” to “PV10MATH”, “PV1READ” to “PV10READ” and “PV1SCIE” to “PV10SCIE” for each school.\n\nThe code below generates the composite PV values.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npvmathsch <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"MATH\"),by= \"CNTSCHID\", data=stu_qqq_SG_clean,export=FALSE,name=\"pvmath_bysch\",folder=data_folder_path)\n\npvreadsch <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"READ\"),by= \"CNTSCHID\", data=stu_qqq_SG_clean,export=FALSE,name=\"pvread_bysch\",folder=data_folder_path)\n\npvsciesch <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"SCIE\"),by= \"CNTSCHID\", data=stu_qqq_SG_clean,export=FALSE,name=\"pvscie_bysch\",folder=data_folder_path)\n```\n:::\n\n\nA plot to show the distribution of students performance in Math, Reading and Science scores across schools was generated using the code below.\n\n::: panel-tabset\n## The Original plot\n\n![](images/clipboard-1617135863.png)\n\nThe author had created a series of error bars across the 3 subjects to represent the subject scores by each school id (164 schools).\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2<- ggplot(pvmathsch, aes(x = as.factor(CNTSCHID), y = Mean)) +\n  geom_boxplot(width = 0.5, position = position_dodge(width = 0.75),lwd=1.5) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    shape = 18,\n    size = 5,\n    position = position_dodge(width = 0.75),\n    color = \"red\"\n  ) +\n  geom_errorbar(\n    aes(ymin = Mean - SD, ymax = Mean + SD),\n    width = 0.8,\n    size=1,\n    position = position_dodge(width = 10)\n  ) +\n  labs(title = \"Math Scores by School\") +\n  ylab(\"Math Score\") +\n  xlab(\"School ID\")+\n  scale_y_continuous(limits=c(0,1000),breaks = seq(0, 1000, by=100))+\n  coord_flip() +\n  theme_minimal(base_size=20)             \n```\n:::\n\n:::\n\n### 3.2.1 Evaluation\n\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Assessment Criteria | Critique/Feedback                                                                                                                                                                                                 | Possible Improvements                                                                                                                                                                                                                                                                      |\n+=====================+===================================================================================================================================================================================================================+============================================================================================================================================================================================================================================================================================+\n| **Clarity**         | 1.  Although the original plot enables me to visualize the differences in scores across schools, I am unclear as to which score this is showing. Is it showing me the range of student scores by school ID?       | 1.  The original subset can still be used, but the code will need to be changed for the revised visualization. This new visualization will retain the original intent to show the different mean scores for each of the 164 schools to visualize the relative performance between schools. |\n|                     |                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                            |\n|                     | 2.  Graph is titled as “Subject Scores by school\", however the code indicates that mean scores +/- one standard deviation were generated instead.                                                                 |                                                                                                                                                                                                                                                                                            |\n|                     |                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                            |\n|                     | 3.  The data subset used for this visualization only has 164 observations and 6 variables. Upon inspecting the data set, this subset is basically the composite mean subject scores for each school.              |                                                                                                                                                                                                                                                                                            |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Aesthetics**      | 1.  The use of a vertically long plot to compare the scores across schools makes it visually challenging and difficult to spot differences in scores, and identify any clusters.                                  | 1.  To revise the design of a vertically long format and re-make it to a horizontally compact visualization, by using bubble plots.                                                                                                                                                        |\n|                     |                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                            |\n|                     | 2.  Since there are 164 schools, the use of a vertically long format makes it difficult to read the school IDs on the Y-axis. There are too many schools to make identification off the Y-axis easy.              | 2.  To minimize axis labels, we can drop axis labels for school id, and only identify and directly annotate the top & bottom 5 schools instead.                                                                                                                                            |\n|                     |                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                            |\n|                     | 3.  The distance between the X-axis, which shows the scores is too far apart from the error bars. I am unable to decipher what are the actual scores or score range for each error bar.                           | 3.  To remove the 2 other repetitive Y-axes to reduce non-data ink.                                                                                                                                                                                                                        |\n|                     |                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                            |\n|                     | 4.  The graph is stiched side by side, resulting in the Y-axis being repeated 3 times. The order of the School IDs are all the same, hence this creates additional non-data ink, that makes the graph too \"busy\". |                                                                                                                                                                                                                                                                                            |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\nExamining the subset used for the original plot in more detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(head(pvmathsch))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  CNTSCHID Freq   Mean  s.e.    SD   s.e\n1 70200001   55 725.21  9.34 59.23  6.38\n2 70200002   37 536.19 17.09 90.27 14.50\n3 70200003   36 739.92 12.30 59.23  7.70\n4 70200004   56 509.61 12.84 86.63  7.71\n5 70200005   37 548.39 13.10 86.30  9.18\n6 70200006   36 485.30 13.90 76.47  8.86\n```\n\n\n:::\n:::\n\n\nThe *pvmathsch* subset table only has 164 observations and 6 variables.\n\n::: callout-note\n## Conclusion\n\nThe data subset can only be used to visualize the mean scores per school ID.\n\nThe original graph is not of a suitable design to help readers easily and quickly understand the disparity in performances between schools.\n\nI will use a new compact visualization to enable the reader to quickly see the differences in school performance.\n:::\n\n### 3.2.2 Sketch of Proposed Design\n\nRough sketch of proposed design is shown below.\n\n![](images/clipboard-150633865.png)\n\n### 3.2.3 Remake\n\nThe original plot does not enable the reader to quickly capture information from the data points.\n\nUsing the exact same data set, I will use the code below to re-make the original graph into a Bubble plots instead. I will employ color as a means to differentiate the mean scores.\n\nI have also added reference lines to show the 10th and 90th percentile scores to help readers easily identify the schools belonging to these two opposite segments.\n\nLastly, I have also added annotations to help readers to quickly identify the top 5 and bottom 5 schools with the best and worst mean scores.\n\n\n::: {.cell .column-body-outset-right}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(ggrepel)\n\n# Identify the top 5 and bottom 5 schools\ntop_5 <- pvmathsch %>% \n  arrange(desc(Mean)) %>%\n  slice(1:5)\n\nbottom_5 <- pvmathsch %>% \n  arrange(Mean) %>%\n  slice(1:5)\n\n# Base plot with points colored by the mean score\np1 <- ggplot(pvmathsch, aes(x = CNTSCHID, y = Mean)) +\n  geom_point(aes(color = Mean), alpha = 0.5, size = 7) +\n  scale_color_gradient(low = \"red\", high = \"green\") +\n  labs(title = \"Mean Math Scores per School\",\n       subtitle = \"5 Schools with the Best & Worst mean scores\",\n       x = \"School ID\",\n       y = \"Mean Math Scores\") +\n  theme_minimal() +\n  theme(axis.text.x = element_blank(),\n        axis.ticks.x = element_blank(),\n        panel.grid.major = element_blank())  # Remove major grid lines\n       \n\n# Annotate the top 5 and bottom 5 schools\np1 <- p1 +\n  geom_text_repel(\n    data = top_5, \n    aes(label = CNTSCHID, y = Mean), \n    color = \"blue\", \n    size = 3, \n    nudge_y = 12,   # Adjust nudge_y if necessary to move text up or down\n    direction = \"y\"\n  ) +\n  geom_text_repel(\n    data = bottom_5, \n    aes(label = CNTSCHID, y = Mean), \n    color = \"blue\", \n    size = 3, \n    nudge_y = -12,  # Adjust nudge_y if necessary to move text up or down\n    direction = \"y\"\n  )\n\n# Calculate the 10th and 90th percentiles\npercentile10 <- quantile(pvmathsch$Mean, probs = 0.10, na.rm = TRUE)\npercentile90 <- quantile(pvmathsch$Mean, probs = 0.90, na.rm = TRUE)\n\n# Add horizontal lines for the 10th and 90th percentiles to your plot\np1 <- p1 + \n  geom_hline(yintercept = percentile10, linetype = \"dashed\", color = \"blue\", size = 0.5) +\n  geom_hline(yintercept = percentile90, linetype = \"dashed\", color = \"blue\", size = 0.5) +\n  geom_text(aes(x = Inf, y = percentile10, label = paste(\"10th Percentile:\", round(percentile10, 2))), \n            hjust = 1.05, vjust = 0, color = \"blue\", size = 3) +\n  geom_text(aes(x = Inf, y = percentile90, label = paste(\"90th Percentile:\", round(percentile90, 2))), \n            hjust = 1.05, vjust = 1, color = \"blue\", size = 3)\n\np1\n```\n\n::: {.cell-output-display}\n![](R_Ex3_files/figure-html/unnamed-chunk-18-1.png){width=768}\n:::\n:::\n\n\n::: callout-tip\n## Revised Plot\n\nThe use of colour can help readers quickly differentiate the scores between schools.\\\n\\\nI have annotated school IDs for the top and bottom 5 schools for readers to quickly identify the \"best\" and \"worst\" schools.\n\nI have also added reference lines for the 10th and 90th Percentile. Here we can quickly see that while most of the 164 schools attain the same range of mean scores, there are a number of schools that outperform the rest.\n\nAnnotating all the 164 school IDs will add too much ink to the plot. Hence, we can consider having another interactive plot (below) for readers to examine the data points in more detail at their descretion.\n:::\n\nFor interactivity, I have used `ggplotly()` to convert this to an interactive graph. With the added interactivity, readers can use the tooltip function to get more information on the data points.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(plotly)\n\n# Convert to an interactive plot\nggplotly(p1, tooltip = c(\"x\", \"y\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-7dce81957798acd2195c\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7dce81957798acd2195c\">{\"x\":{\"data\":[{\"x\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164],\"y\":[725.21000000000004,536.19000000000005,739.91999999999996,509.61000000000001,548.38999999999999,485.30000000000001,578.63,566.75,559.75999999999999,535.45000000000005,597.92999999999995,655.37,519.48000000000002,577.32000000000005,538.60000000000002,569.57000000000005,583.48000000000002,680.12,591.59000000000003,650.58000000000004,498.98000000000002,564.94000000000005,551.65999999999997,510.69,531.98000000000002,549.11000000000001,527.60000000000002,635.08000000000004,493.30000000000001,509.68000000000001,567.53999999999996,560.32000000000005,645.74000000000001,528.19000000000005,648.22000000000003,528.73000000000002,558.95000000000005,521.25,567.57000000000005,669.92999999999995,564.25,523.97000000000003,565,688.19000000000005,529.28999999999996,605.61000000000001,588.50999999999999,556.77999999999997,559.80999999999995,587.58000000000004,560.76999999999998,580.63999999999999,676.07000000000005,543.41999999999996,505.72000000000003,473.60000000000002,566.37,536.29999999999995,546.02999999999997,657.10000000000002,568.51999999999998,684.12,609.13,651.46000000000004,499.51999999999998,644.25,571.27999999999997,570.03999999999996,517.10000000000002,500.33999999999997,646.80999999999995,562.75999999999999,636.67999999999995,517.41999999999996,650.38,587.23000000000002,548.79999999999995,595.22000000000003,619.02999999999997,581.66999999999996,603.99000000000001,671.41999999999996,562.75999999999999,505.99000000000001,557.05999999999995,537.82000000000005,566.51999999999998,591.35000000000002,545.75,644.64999999999998,646.99000000000001,590.86000000000001,549.84000000000003,544.25,620.34000000000003,574.82000000000005,537.60000000000002,534.48000000000002,513.01999999999998,494.43000000000001,699.59000000000003,519.12,564.01999999999998,634.83000000000004,539.09000000000003,564.53999999999996,542.28999999999996,591.72000000000003,496.29000000000002,688.50999999999999,585.26999999999998,587.28999999999996,663.19000000000005,562.17999999999995,405.42000000000002,507.33999999999997,574.25,524.89999999999998,679.03999999999996,588.32000000000005,529.49000000000001,579.92999999999995,542.10000000000002,562.16999999999996,583.63,574.41999999999996,517.29999999999995,505.60000000000002,503.98000000000002,586.41999999999996,566.47000000000003,658.17999999999995,556.00999999999999,521.41999999999996,615.23000000000002,554.99000000000001,500.81999999999999,585.40999999999997,690.24000000000001,511.41000000000003,505.89999999999998,644.08000000000004,506.18000000000001,589.88,543.12,536.66999999999996,565.66999999999996,580.97000000000003,386.48000000000002,564.99000000000001,484.38,534.80999999999995,514.54999999999995,685.36000000000001,576.17999999999995,555.21000000000004,551.78999999999996,579.23000000000002,562.85000000000002,526.33000000000004,610.73000000000002,533.32000000000005,470.51999999999998,534.69000000000005],\"text\":[\"CNTSCHID: 70200001<br />Mean: 725.21\",\"CNTSCHID: 70200002<br />Mean: 536.19\",\"CNTSCHID: 70200003<br />Mean: 739.92\",\"CNTSCHID: 70200004<br />Mean: 509.61\",\"CNTSCHID: 70200005<br />Mean: 548.39\",\"CNTSCHID: 70200006<br />Mean: 485.30\",\"CNTSCHID: 70200007<br />Mean: 578.63\",\"CNTSCHID: 70200008<br />Mean: 566.75\",\"CNTSCHID: 70200009<br />Mean: 559.76\",\"CNTSCHID: 70200010<br />Mean: 535.45\",\"CNTSCHID: 70200011<br />Mean: 597.93\",\"CNTSCHID: 70200012<br />Mean: 655.37\",\"CNTSCHID: 70200013<br />Mean: 519.48\",\"CNTSCHID: 70200014<br />Mean: 577.32\",\"CNTSCHID: 70200015<br />Mean: 538.60\",\"CNTSCHID: 70200016<br />Mean: 569.57\",\"CNTSCHID: 70200017<br />Mean: 583.48\",\"CNTSCHID: 70200018<br />Mean: 680.12\",\"CNTSCHID: 70200019<br />Mean: 591.59\",\"CNTSCHID: 70200020<br />Mean: 650.58\",\"CNTSCHID: 70200021<br />Mean: 498.98\",\"CNTSCHID: 70200022<br />Mean: 564.94\",\"CNTSCHID: 70200023<br />Mean: 551.66\",\"CNTSCHID: 70200024<br />Mean: 510.69\",\"CNTSCHID: 70200025<br />Mean: 531.98\",\"CNTSCHID: 70200026<br />Mean: 549.11\",\"CNTSCHID: 70200027<br />Mean: 527.60\",\"CNTSCHID: 70200028<br />Mean: 635.08\",\"CNTSCHID: 70200029<br />Mean: 493.30\",\"CNTSCHID: 70200030<br />Mean: 509.68\",\"CNTSCHID: 70200031<br />Mean: 567.54\",\"CNTSCHID: 70200032<br />Mean: 560.32\",\"CNTSCHID: 70200033<br />Mean: 645.74\",\"CNTSCHID: 70200034<br />Mean: 528.19\",\"CNTSCHID: 70200035<br />Mean: 648.22\",\"CNTSCHID: 70200036<br />Mean: 528.73\",\"CNTSCHID: 70200037<br />Mean: 558.95\",\"CNTSCHID: 70200038<br />Mean: 521.25\",\"CNTSCHID: 70200039<br />Mean: 567.57\",\"CNTSCHID: 70200040<br />Mean: 669.93\",\"CNTSCHID: 70200041<br />Mean: 564.25\",\"CNTSCHID: 70200042<br />Mean: 523.97\",\"CNTSCHID: 70200043<br />Mean: 565.00\",\"CNTSCHID: 70200044<br />Mean: 688.19\",\"CNTSCHID: 70200045<br />Mean: 529.29\",\"CNTSCHID: 70200046<br />Mean: 605.61\",\"CNTSCHID: 70200047<br />Mean: 588.51\",\"CNTSCHID: 70200048<br />Mean: 556.78\",\"CNTSCHID: 70200049<br />Mean: 559.81\",\"CNTSCHID: 70200050<br />Mean: 587.58\",\"CNTSCHID: 70200051<br />Mean: 560.77\",\"CNTSCHID: 70200052<br />Mean: 580.64\",\"CNTSCHID: 70200053<br />Mean: 676.07\",\"CNTSCHID: 70200054<br />Mean: 543.42\",\"CNTSCHID: 70200055<br />Mean: 505.72\",\"CNTSCHID: 70200056<br />Mean: 473.60\",\"CNTSCHID: 70200057<br />Mean: 566.37\",\"CNTSCHID: 70200058<br />Mean: 536.30\",\"CNTSCHID: 70200059<br />Mean: 546.03\",\"CNTSCHID: 70200060<br />Mean: 657.10\",\"CNTSCHID: 70200061<br />Mean: 568.52\",\"CNTSCHID: 70200062<br />Mean: 684.12\",\"CNTSCHID: 70200063<br />Mean: 609.13\",\"CNTSCHID: 70200064<br />Mean: 651.46\",\"CNTSCHID: 70200065<br />Mean: 499.52\",\"CNTSCHID: 70200066<br />Mean: 644.25\",\"CNTSCHID: 70200067<br />Mean: 571.28\",\"CNTSCHID: 70200068<br />Mean: 570.04\",\"CNTSCHID: 70200069<br />Mean: 517.10\",\"CNTSCHID: 70200070<br />Mean: 500.34\",\"CNTSCHID: 70200071<br />Mean: 646.81\",\"CNTSCHID: 70200072<br />Mean: 562.76\",\"CNTSCHID: 70200073<br />Mean: 636.68\",\"CNTSCHID: 70200074<br />Mean: 517.42\",\"CNTSCHID: 70200075<br />Mean: 650.38\",\"CNTSCHID: 70200076<br />Mean: 587.23\",\"CNTSCHID: 70200077<br />Mean: 548.80\",\"CNTSCHID: 70200078<br />Mean: 595.22\",\"CNTSCHID: 70200079<br />Mean: 619.03\",\"CNTSCHID: 70200080<br />Mean: 581.67\",\"CNTSCHID: 70200081<br />Mean: 603.99\",\"CNTSCHID: 70200082<br />Mean: 671.42\",\"CNTSCHID: 70200083<br />Mean: 562.76\",\"CNTSCHID: 70200084<br />Mean: 505.99\",\"CNTSCHID: 70200085<br />Mean: 557.06\",\"CNTSCHID: 70200086<br />Mean: 537.82\",\"CNTSCHID: 70200087<br />Mean: 566.52\",\"CNTSCHID: 70200088<br />Mean: 591.35\",\"CNTSCHID: 70200089<br />Mean: 545.75\",\"CNTSCHID: 70200090<br />Mean: 644.65\",\"CNTSCHID: 70200091<br />Mean: 646.99\",\"CNTSCHID: 70200092<br />Mean: 590.86\",\"CNTSCHID: 70200093<br />Mean: 549.84\",\"CNTSCHID: 70200094<br />Mean: 544.25\",\"CNTSCHID: 70200095<br />Mean: 620.34\",\"CNTSCHID: 70200096<br />Mean: 574.82\",\"CNTSCHID: 70200097<br />Mean: 537.60\",\"CNTSCHID: 70200098<br />Mean: 534.48\",\"CNTSCHID: 70200099<br />Mean: 513.02\",\"CNTSCHID: 70200100<br />Mean: 494.43\",\"CNTSCHID: 70200101<br />Mean: 699.59\",\"CNTSCHID: 70200102<br />Mean: 519.12\",\"CNTSCHID: 70200103<br />Mean: 564.02\",\"CNTSCHID: 70200104<br />Mean: 634.83\",\"CNTSCHID: 70200105<br />Mean: 539.09\",\"CNTSCHID: 70200106<br />Mean: 564.54\",\"CNTSCHID: 70200107<br />Mean: 542.29\",\"CNTSCHID: 70200108<br />Mean: 591.72\",\"CNTSCHID: 70200109<br />Mean: 496.29\",\"CNTSCHID: 70200110<br />Mean: 688.51\",\"CNTSCHID: 70200111<br />Mean: 585.27\",\"CNTSCHID: 70200112<br />Mean: 587.29\",\"CNTSCHID: 70200113<br />Mean: 663.19\",\"CNTSCHID: 70200114<br />Mean: 562.18\",\"CNTSCHID: 70200115<br />Mean: 405.42\",\"CNTSCHID: 70200116<br />Mean: 507.34\",\"CNTSCHID: 70200117<br />Mean: 574.25\",\"CNTSCHID: 70200118<br />Mean: 524.90\",\"CNTSCHID: 70200119<br />Mean: 679.04\",\"CNTSCHID: 70200120<br />Mean: 588.32\",\"CNTSCHID: 70200121<br />Mean: 529.49\",\"CNTSCHID: 70200122<br />Mean: 579.93\",\"CNTSCHID: 70200123<br />Mean: 542.10\",\"CNTSCHID: 70200124<br />Mean: 562.17\",\"CNTSCHID: 70200125<br />Mean: 583.63\",\"CNTSCHID: 70200126<br />Mean: 574.42\",\"CNTSCHID: 70200127<br />Mean: 517.30\",\"CNTSCHID: 70200128<br />Mean: 505.60\",\"CNTSCHID: 70200129<br />Mean: 503.98\",\"CNTSCHID: 70200130<br />Mean: 586.42\",\"CNTSCHID: 70200131<br />Mean: 566.47\",\"CNTSCHID: 70200132<br />Mean: 658.18\",\"CNTSCHID: 70200133<br />Mean: 556.01\",\"CNTSCHID: 70200134<br />Mean: 521.42\",\"CNTSCHID: 70200135<br />Mean: 615.23\",\"CNTSCHID: 70200136<br />Mean: 554.99\",\"CNTSCHID: 70200137<br />Mean: 500.82\",\"CNTSCHID: 70200138<br />Mean: 585.41\",\"CNTSCHID: 70200139<br />Mean: 690.24\",\"CNTSCHID: 70200140<br />Mean: 511.41\",\"CNTSCHID: 70200141<br />Mean: 505.90\",\"CNTSCHID: 70200142<br />Mean: 644.08\",\"CNTSCHID: 70200143<br />Mean: 506.18\",\"CNTSCHID: 70200144<br />Mean: 589.88\",\"CNTSCHID: 70200145<br />Mean: 543.12\",\"CNTSCHID: 70200146<br />Mean: 536.67\",\"CNTSCHID: 70200147<br />Mean: 565.67\",\"CNTSCHID: 70200148<br />Mean: 580.97\",\"CNTSCHID: 70200149<br />Mean: 386.48\",\"CNTSCHID: 70200151<br />Mean: 564.99\",\"CNTSCHID: 70200152<br />Mean: 484.38\",\"CNTSCHID: 70200153<br />Mean: 534.81\",\"CNTSCHID: 70200154<br />Mean: 514.55\",\"CNTSCHID: 70200155<br />Mean: 685.36\",\"CNTSCHID: 70200156<br />Mean: 576.18\",\"CNTSCHID: 70200157<br />Mean: 555.21\",\"CNTSCHID: 70200158<br />Mean: 551.79\",\"CNTSCHID: 70200159<br />Mean: 579.23\",\"CNTSCHID: 70200160<br />Mean: 562.85\",\"CNTSCHID: 70200161<br />Mean: 526.33\",\"CNTSCHID: 70200162<br />Mean: 610.73\",\"CNTSCHID: 70200163<br />Mean: 533.32\",\"CNTSCHID: 70200164<br />Mean: 470.52\",\"CNTSCHID: 70200165<br />Mean: 534.69\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":[\"rgba(67,248,0,1)\",\"rgba(211,156,0,1)\",\"rgba(0,255,0,1)\",\"rgba(221,141,0,1)\",\"rgba(207,163,0,1)\",\"rgba(229,126,0,1)\",\"rgba(194,179,0,1)\",\"rgba(199,173,0,1)\",\"rgba(202,169,0,1)\",\"rgba(212,156,0,1)\",\"rgba(184,189,0,1)\",\"rgba(149,217,0,1)\",\"rgba(218,147,0,1)\",\"rgba(194,178,0,1)\",\"rgba(211,158,0,1)\",\"rgba(198,174,0,1)\",\"rgba(191,182,0,1)\",\"rgba(128,228,0,1)\",\"rgba(187,186,0,1)\",\"rgba(152,214,0,1)\",\"rgba(225,134,0,1)\",\"rgba(200,172,0,1)\",\"rgba(205,165,0,1)\",\"rgba(221,142,0,1)\",\"rgba(213,154,0,1)\",\"rgba(206,163,0,1)\",\"rgba(215,151,0,1)\",\"rgba(163,207,0,1)\",\"rgba(226,131,0,1)\",\"rgba(221,141,0,1)\",\"rgba(199,173,0,1)\",\"rgba(202,169,0,1)\",\"rgba(156,212,0,1)\",\"rgba(214,152,0,1)\",\"rgba(154,213,0,1)\",\"rgba(214,152,0,1)\",\"rgba(202,169,0,1)\",\"rgba(217,148,0,1)\",\"rgba(199,173,0,1)\",\"rgba(137,223,0,1)\",\"rgba(200,172,0,1)\",\"rgba(216,149,0,1)\",\"rgba(200,172,0,1)\",\"rgba(120,232,0,1)\",\"rgba(214,152,0,1)\",\"rgba(180,193,0,1)\",\"rgba(189,184,0,1)\",\"rgba(203,168,0,1)\",\"rgba(202,169,0,1)\",\"rgba(189,184,0,1)\",\"rgba(202,170,0,1)\",\"rgba(193,180,0,1)\",\"rgba(132,226,0,1)\",\"rgba(209,160,0,1)\",\"rgba(222,139,0,1)\",\"rgba(233,118,0,1)\",\"rgba(199,173,0,1)\",\"rgba(211,156,0,1)\",\"rgba(208,162,0,1)\",\"rgba(148,217,0,1)\",\"rgba(198,174,0,1)\",\"rgba(124,230,0,1)\",\"rgba(178,194,0,1)\",\"rgba(152,215,0,1)\",\"rgba(224,135,0,1)\",\"rgba(157,211,0,1)\",\"rgba(197,175,0,1)\",\"rgba(198,175,0,1)\",\"rgba(218,145,0,1)\",\"rgba(224,135,0,1)\",\"rgba(155,213,0,1)\",\"rgba(201,171,0,1)\",\"rgba(162,208,0,1)\",\"rgba(218,146,0,1)\",\"rgba(153,214,0,1)\",\"rgba(190,183,0,1)\",\"rgba(207,163,0,1)\",\"rgba(186,187,0,1)\",\"rgba(173,199,0,1)\",\"rgba(192,181,0,1)\",\"rgba(181,192,0,1)\",\"rgba(136,224,0,1)\",\"rgba(201,171,0,1)\",\"rgba(222,139,0,1)\",\"rgba(203,168,0,1)\",\"rgba(211,157,0,1)\",\"rgba(199,173,0,1)\",\"rgba(188,186,0,1)\",\"rgba(208,162,0,1)\",\"rgba(157,212,0,1)\",\"rgba(155,213,0,1)\",\"rgba(188,185,0,1)\",\"rgba(206,164,0,1)\",\"rgba(208,161,0,1)\",\"rgba(172,200,0,1)\",\"rgba(195,177,0,1)\",\"rgba(211,157,0,1)\",\"rgba(212,155,0,1)\",\"rgba(220,143,0,1)\",\"rgba(226,131,0,1)\",\"rgba(108,237,0,1)\",\"rgba(218,147,0,1)\",\"rgba(200,171,0,1)\",\"rgba(163,207,0,1)\",\"rgba(210,158,0,1)\",\"rgba(200,172,0,1)\",\"rgba(209,160,0,1)\",\"rgba(187,186,0,1)\",\"rgba(226,133,0,1)\",\"rgba(120,232,0,1)\",\"rgba(191,182,0,1)\",\"rgba(190,183,0,1)\",\"rgba(143,220,0,1)\",\"rgba(201,170,0,1)\",\"rgba(251,53,0,1)\",\"rgba(222,140,0,1)\",\"rgba(196,177,0,1)\",\"rgba(216,150,0,1)\",\"rgba(129,228,0,1)\",\"rgba(189,184,0,1)\",\"rgba(214,153,0,1)\",\"rgba(193,180,0,1)\",\"rgba(209,160,0,1)\",\"rgba(201,170,0,1)\",\"rgba(191,182,0,1)\",\"rgba(196,177,0,1)\",\"rgba(218,145,0,1)\",\"rgba(222,138,0,1)\",\"rgba(223,137,0,1)\",\"rgba(190,183,0,1)\",\"rgba(199,173,0,1)\",\"rgba(147,218,0,1)\",\"rgba(204,167,0,1)\",\"rgba(217,148,0,1)\",\"rgba(175,197,0,1)\",\"rgba(204,167,0,1)\",\"rgba(224,136,0,1)\",\"rgba(190,183,0,1)\",\"rgba(118,233,0,1)\",\"rgba(220,142,0,1)\",\"rgba(222,139,0,1)\",\"rgba(157,211,0,1)\",\"rgba(222,139,0,1)\",\"rgba(188,185,0,1)\",\"rgba(209,160,0,1)\",\"rgba(211,157,0,1)\",\"rgba(199,172,0,1)\",\"rgba(193,180,0,1)\",\"rgba(255,0,0,1)\",\"rgba(200,172,0,1)\",\"rgba(229,125,0,1)\",\"rgba(212,156,0,1)\",\"rgba(219,144,0,1)\",\"rgba(123,230,0,1)\",\"rgba(195,178,0,1)\",\"rgba(204,167,0,1)\",\"rgba(205,165,0,1)\",\"rgba(193,179,0,1)\",\"rgba(201,171,0,1)\",\"rgba(215,151,0,1)\",\"rgba(177,195,0,1)\",\"rgba(213,155,0,1)\",\"rgba(233,115,0,1)\",\"rgba(212,155,0,1)\"],\"opacity\":0.5,\"size\":26.45669291338583,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":[\"rgba(67,248,0,1)\",\"rgba(211,156,0,1)\",\"rgba(0,255,0,1)\",\"rgba(221,141,0,1)\",\"rgba(207,163,0,1)\",\"rgba(229,126,0,1)\",\"rgba(194,179,0,1)\",\"rgba(199,173,0,1)\",\"rgba(202,169,0,1)\",\"rgba(212,156,0,1)\",\"rgba(184,189,0,1)\",\"rgba(149,217,0,1)\",\"rgba(218,147,0,1)\",\"rgba(194,178,0,1)\",\"rgba(211,158,0,1)\",\"rgba(198,174,0,1)\",\"rgba(191,182,0,1)\",\"rgba(128,228,0,1)\",\"rgba(187,186,0,1)\",\"rgba(152,214,0,1)\",\"rgba(225,134,0,1)\",\"rgba(200,172,0,1)\",\"rgba(205,165,0,1)\",\"rgba(221,142,0,1)\",\"rgba(213,154,0,1)\",\"rgba(206,163,0,1)\",\"rgba(215,151,0,1)\",\"rgba(163,207,0,1)\",\"rgba(226,131,0,1)\",\"rgba(221,141,0,1)\",\"rgba(199,173,0,1)\",\"rgba(202,169,0,1)\",\"rgba(156,212,0,1)\",\"rgba(214,152,0,1)\",\"rgba(154,213,0,1)\",\"rgba(214,152,0,1)\",\"rgba(202,169,0,1)\",\"rgba(217,148,0,1)\",\"rgba(199,173,0,1)\",\"rgba(137,223,0,1)\",\"rgba(200,172,0,1)\",\"rgba(216,149,0,1)\",\"rgba(200,172,0,1)\",\"rgba(120,232,0,1)\",\"rgba(214,152,0,1)\",\"rgba(180,193,0,1)\",\"rgba(189,184,0,1)\",\"rgba(203,168,0,1)\",\"rgba(202,169,0,1)\",\"rgba(189,184,0,1)\",\"rgba(202,170,0,1)\",\"rgba(193,180,0,1)\",\"rgba(132,226,0,1)\",\"rgba(209,160,0,1)\",\"rgba(222,139,0,1)\",\"rgba(233,118,0,1)\",\"rgba(199,173,0,1)\",\"rgba(211,156,0,1)\",\"rgba(208,162,0,1)\",\"rgba(148,217,0,1)\",\"rgba(198,174,0,1)\",\"rgba(124,230,0,1)\",\"rgba(178,194,0,1)\",\"rgba(152,215,0,1)\",\"rgba(224,135,0,1)\",\"rgba(157,211,0,1)\",\"rgba(197,175,0,1)\",\"rgba(198,175,0,1)\",\"rgba(218,145,0,1)\",\"rgba(224,135,0,1)\",\"rgba(155,213,0,1)\",\"rgba(201,171,0,1)\",\"rgba(162,208,0,1)\",\"rgba(218,146,0,1)\",\"rgba(153,214,0,1)\",\"rgba(190,183,0,1)\",\"rgba(207,163,0,1)\",\"rgba(186,187,0,1)\",\"rgba(173,199,0,1)\",\"rgba(192,181,0,1)\",\"rgba(181,192,0,1)\",\"rgba(136,224,0,1)\",\"rgba(201,171,0,1)\",\"rgba(222,139,0,1)\",\"rgba(203,168,0,1)\",\"rgba(211,157,0,1)\",\"rgba(199,173,0,1)\",\"rgba(188,186,0,1)\",\"rgba(208,162,0,1)\",\"rgba(157,212,0,1)\",\"rgba(155,213,0,1)\",\"rgba(188,185,0,1)\",\"rgba(206,164,0,1)\",\"rgba(208,161,0,1)\",\"rgba(172,200,0,1)\",\"rgba(195,177,0,1)\",\"rgba(211,157,0,1)\",\"rgba(212,155,0,1)\",\"rgba(220,143,0,1)\",\"rgba(226,131,0,1)\",\"rgba(108,237,0,1)\",\"rgba(218,147,0,1)\",\"rgba(200,171,0,1)\",\"rgba(163,207,0,1)\",\"rgba(210,158,0,1)\",\"rgba(200,172,0,1)\",\"rgba(209,160,0,1)\",\"rgba(187,186,0,1)\",\"rgba(226,133,0,1)\",\"rgba(120,232,0,1)\",\"rgba(191,182,0,1)\",\"rgba(190,183,0,1)\",\"rgba(143,220,0,1)\",\"rgba(201,170,0,1)\",\"rgba(251,53,0,1)\",\"rgba(222,140,0,1)\",\"rgba(196,177,0,1)\",\"rgba(216,150,0,1)\",\"rgba(129,228,0,1)\",\"rgba(189,184,0,1)\",\"rgba(214,153,0,1)\",\"rgba(193,180,0,1)\",\"rgba(209,160,0,1)\",\"rgba(201,170,0,1)\",\"rgba(191,182,0,1)\",\"rgba(196,177,0,1)\",\"rgba(218,145,0,1)\",\"rgba(222,138,0,1)\",\"rgba(223,137,0,1)\",\"rgba(190,183,0,1)\",\"rgba(199,173,0,1)\",\"rgba(147,218,0,1)\",\"rgba(204,167,0,1)\",\"rgba(217,148,0,1)\",\"rgba(175,197,0,1)\",\"rgba(204,167,0,1)\",\"rgba(224,136,0,1)\",\"rgba(190,183,0,1)\",\"rgba(118,233,0,1)\",\"rgba(220,142,0,1)\",\"rgba(222,139,0,1)\",\"rgba(157,211,0,1)\",\"rgba(222,139,0,1)\",\"rgba(188,185,0,1)\",\"rgba(209,160,0,1)\",\"rgba(211,157,0,1)\",\"rgba(199,172,0,1)\",\"rgba(193,180,0,1)\",\"rgba(255,0,0,1)\",\"rgba(200,172,0,1)\",\"rgba(229,125,0,1)\",\"rgba(212,156,0,1)\",\"rgba(219,144,0,1)\",\"rgba(123,230,0,1)\",\"rgba(195,178,0,1)\",\"rgba(204,167,0,1)\",\"rgba(205,165,0,1)\",\"rgba(193,179,0,1)\",\"rgba(201,171,0,1)\",\"rgba(215,151,0,1)\",\"rgba(177,195,0,1)\",\"rgba(213,155,0,1)\",\"rgba(233,115,0,1)\",\"rgba(212,155,0,1)\"]}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"mode\":\"\",\"frame\":null},{\"x\":[0.40000000000000002,164.59999999999999],\"y\":[505.92699999999996,505.92699999999996],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,255,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0.40000000000000002,164.59999999999999],\"y\":[654.19700000000012,654.19700000000012],\"text\":\"\",\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,255,1)\",\"dash\":\"dash\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"y\":[505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996,505.92699999999996],\"text\":[\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\",\"10th Percentile: 505.93\"],\"hovertext\":[\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\",\"x: Inf<br />percentile10: 505.927\"],\"textfont\":{\"size\":11.338582677165356,\"color\":\"rgba(0,0,255,1)\"},\"type\":\"scatter\",\"mode\":\"text\",\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"y\":[654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012,654.19700000000012],\"text\":[\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\",\"90th Percentile: 654.2\"],\"hovertext\":[\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\",\"x: Inf<br />percentile90: 654.197\"],\"textfont\":{\"size\":11.338582677165356,\"color\":\"rgba(0,0,255,1)\"},\"type\":\"scatter\",\"mode\":\"text\",\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[1],\"y\":[400],\"name\":\"a6a9e335d22c8ac4385a03bfc7e7aa26\",\"type\":\"scatter\",\"mode\":\"markers\",\"opacity\":0,\"hoverinfo\":\"skip\",\"showlegend\":false,\"marker\":{\"color\":[0,1],\"colorscale\":[[0,\"#FF0000\"],[0.0033444816053511024,\"#FF0700\"],[0.0066889632107023653,\"#FE0E00\"],[0.010033444816053467,\"#FE1300\"],[0.013377926421404731,\"#FE1700\"],[0.016722408026755831,\"#FE1B00\"],[0.020066889632107097,\"#FD1E00\"],[0.023411371237458199,\"#FD2100\"],[0.026755852842809302,\"#FD2400\"],[0.030100334448160564,\"#FD2700\"],[0.033444816053511663,\"#FC2900\"],[0.036789297658862928,\"#FC2B00\"],[0.040133779264214034,\"#FC2D00\"],[0.043478260869565293,\"#FC3000\"],[0.046822742474916398,\"#FB3100\"],[0.050167224080267497,\"#FB3300\"],[0.053511705685618763,\"#FB3500\"],[0.056856187290969862,\"#FA3700\"],[0.060200668896321127,\"#FA3900\"],[0.063545150501672226,\"#FA3A00\"],[0.066889632107023325,\"#FA3C00\"],[0.070234113712374591,\"#F93D00\"],[0.073578595317725703,\"#F93F00\"],[0.076923076923076955,\"#F94100\"],[0.080267558528428068,\"#F84200\"],[0.08361204013377932,\"#F84300\"],[0.086956521739130432,\"#F84500\"],[0.090301003344481531,\"#F84600\"],[0.093645484949832797,\"#F74700\"],[0.096989966555183896,\"#F74900\"],[0.10033444816053516,\"#F74A00\"],[0.10367892976588626,\"#F64B00\"],[0.10702341137123753,\"#F64D00\"],[0.11036789297658862,\"#F64E00\"],[0.11371237458193972,\"#F54F00\"],[0.11705685618729099,\"#F55000\"],[0.12040133779264209,\"#F55100\"],[0.12374581939799335,\"#F55300\"],[0.12709030100334445,\"#F45400\"],[0.13043478260869573,\"#F45500\"],[0.13377926421404682,\"#F45600\"],[0.13712374581939793,\"#F35700\"],[0.14046822742474918,\"#F35800\"],[0.14381270903010029,\"#F35900\"],[0.14715719063545155,\"#F25A00\"],[0.15050167224080266,\"#F25B00\"],[0.15384615384615391,\"#F25C00\"],[0.15719063545150502,\"#F15D00\"],[0.16053511705685614,\"#F15E00\"],[0.16387959866220739,\"#F15F00\"],[0.1672240802675585,\"#F16000\"],[0.17056856187290975,\"#F06100\"],[0.17391304347826086,\"#F06200\"],[0.17725752508361212,\"#F06300\"],[0.18060200668896323,\"#EF6400\"],[0.18394648829431431,\"#EF6500\"],[0.18729096989966559,\"#EF6600\"],[0.19063545150501668,\"#EE6700\"],[0.19397993311036796,\"#EE6800\"],[0.19732441471571904,\"#EE6900\"],[0.20066889632107032,\"#ED6A00\"],[0.20401337792642141,\"#ED6B00\"],[0.20735785953177252,\"#ED6C00\"],[0.21070234113712377,\"#EC6C00\"],[0.21404682274247488,\"#EC6D00\"],[0.21739130434782614,\"#EC6E00\"],[0.22073578595317725,\"#EB6F00\"],[0.22408026755852853,\"#EB7000\"],[0.22742474916387961,\"#EB7100\"],[0.23076923076923073,\"#EA7200\"],[0.23411371237458198,\"#EA7300\"],[0.23745819397993309,\"#EA7300\"],[0.24080267558528434,\"#E97400\"],[0.24414715719063546,\"#E97500\"],[0.24749163879598671,\"#E87600\"],[0.25083612040133779,\"#E87700\"],[0.2541806020066889,\"#E87800\"],[0.25752508361204018,\"#E77800\"],[0.2608695652173913,\"#E77900\"],[0.26421404682274252,\"#E77A00\"],[0.26755852842809363,\"#E67B00\"],[0.27090301003344491,\"#E67C00\"],[0.27424749163879603,\"#E67C00\"],[0.27759197324414714,\"#E57D00\"],[0.28093645484949836,\"#E57E00\"],[0.28428093645484948,\"#E47F00\"],[0.28762541806020059,\"#E47F00\"],[0.29096989966555187,\"#E48000\"],[0.29431438127090309,\"#E38100\"],[0.2976588628762542,\"#E38200\"],[0.30100334448160532,\"#E38200\"],[0.3043478260869566,\"#E28300\"],[0.30769230769230765,\"#E28400\"],[0.31103678929765877,\"#E18500\"],[0.31438127090301005,\"#E18500\"],[0.31772575250836133,\"#E18600\"],[0.32107023411371244,\"#E08700\"],[0.3244147157190635,\"#E08800\"],[0.32775919732441477,\"#E08800\"],[0.33110367892976589,\"#DF8900\"],[0.334448160535117,\"#DF8A00\"],[0.33779264214046822,\"#DE8B00\"],[0.3411371237458195,\"#DE8B00\"],[0.34448160535117062,\"#DE8C00\"],[0.34782608695652173,\"#DD8D00\"],[0.35117056856187295,\"#DD8D00\"],[0.35451505016722407,\"#DC8E00\"],[0.35785953177257518,\"#DC8F00\"],[0.36120401337792646,\"#DC9000\"],[0.36454849498327768,\"#DB9000\"],[0.36789297658862863,\"#DB9100\"],[0.37123745819397991,\"#DA9200\"],[0.37458193979933119,\"#DA9200\"],[0.37792642140468213,\"#D99300\"],[0.38127090301003336,\"#D99400\"],[0.38461538461538464,\"#D99400\"],[0.38795986622073592,\"#D89500\"],[0.39130434782608714,\"#D89600\"],[0.39464882943143809,\"#D79700\"],[0.39799331103678937,\"#D79700\"],[0.40133779264214064,\"#D69800\"],[0.40468227424749159,\"#D69900\"],[0.40802675585284282,\"#D69900\"],[0.41137123745819409,\"#D59A00\"],[0.41471571906354504,\"#D59B00\"],[0.41806020066889632,\"#D49B00\"],[0.42140468227424754,\"#D49C00\"],[0.42474916387959849,\"#D39D00\"],[0.42809364548494977,\"#D39D00\"],[0.43143812709030105,\"#D29E00\"],[0.43478260869565227,\"#D29F00\"],[0.43812709030100355,\"#D19F00\"],[0.4414715719063545,\"#D1A000\"],[0.44481605351170578,\"#D1A000\"],[0.44816053511705706,\"#D0A100\"],[0.45150501672240795,\"#D0A200\"],[0.45484949832775923,\"#CFA200\"],[0.45819397993311051,\"#CFA300\"],[0.46153846153846145,\"#CEA400\"],[0.46488294314381268,\"#CEA400\"],[0.46822742474916396,\"#CDA500\"],[0.4715719063545149,\"#CDA600\"],[0.47491638795986618,\"#CCA600\"],[0.47826086956521741,\"#CCA700\"],[0.48160535117056869,\"#CBA800\"],[0.48494983277591963,\"#CBA800\"],[0.48829431438127091,\"#CAA900\"],[0.49163879598662219,\"#CAA900\"],[0.49498327759197341,\"#C9AA00\"],[0.49832775919732436,\"#C9AB00\"],[0.50167224080267558,\"#C8AB00\"],[0.50501672240802686,\"#C8AC00\"],[0.50836120401337781,\"#C7AD00\"],[0.51170568561872909,\"#C7AD00\"],[0.51505016722408037,\"#C6AE00\"],[0.51839464882943131,\"#C6AE00\"],[0.52173913043478259,\"#C5AF00\"],[0.52508361204013387,\"#C5B000\"],[0.52842809364548504,\"#C4B000\"],[0.53177257525083599,\"#C4B100\"],[0.53511705685618727,\"#C3B100\"],[0.53846153846153855,\"#C2B200\"],[0.54180602006688983,\"#C2B300\"],[0.54515050167224077,\"#C1B300\"],[0.54849498327759205,\"#C1B400\"],[0.55183946488294333,\"#C0B500\"],[0.55518394648829428,\"#C0B500\"],[0.55852842809364545,\"#BFB600\"],[0.56187290969899673,\"#BFB600\"],[0.56521739130434767,\"#BEB700\"],[0.56856187290969895,\"#BDB800\"],[0.57190635451505023,\"#BDB800\"],[0.57525083612040118,\"#BCB900\"],[0.57859531772575246,\"#BCB900\"],[0.58193979933110374,\"#BBBA00\"],[0.5852842809364549,\"#BBBB00\"],[0.58862876254180618,\"#BABB00\"],[0.59197324414715713,\"#B9BC00\"],[0.59531772575250841,\"#B9BC00\"],[0.59866220735785969,\"#B8BD00\"],[0.60200668896321063,\"#B8BE00\"],[0.60535117056856191,\"#B7BE00\"],[0.60869565217391319,\"#B6BF00\"],[0.61204013377926414,\"#B6BF00\"],[0.61538461538461531,\"#B5C000\"],[0.61872909698996659,\"#B4C000\"],[0.62207357859531753,\"#B4C100\"],[0.62541806020066881,\"#B3C200\"],[0.62876254180602009,\"#B3C200\"],[0.63210702341137137,\"#B2C300\"],[0.63545150501672265,\"#B1C300\"],[0.6387959866220736,\"#B1C400\"],[0.64214046822742488,\"#B0C500\"],[0.64548494983277604,\"#AFC500\"],[0.64882943143812699,\"#AFC600\"],[0.65217391304347827,\"#AEC600\"],[0.65551839464882955,\"#ADC700\"],[0.6588628762541805,\"#ADC700\"],[0.66220735785953178,\"#ACC800\"],[0.66555183946488305,\"#ABC900\"],[0.668896321070234,\"#AAC900\"],[0.67224080267558517,\"#AACA00\"],[0.67558528428093645,\"#A9CA00\"],[0.67892976588628773,\"#A8CB00\"],[0.68227424749163901,\"#A8CB00\"],[0.68561872909698995,\"#A7CC00\"],[0.68896321070234123,\"#A6CD00\"],[0.69230769230769251,\"#A5CD00\"],[0.69565217391304346,\"#A5CE00\"],[0.69899665551839474,\"#A4CE00\"],[0.70234113712374591,\"#A3CF00\"],[0.70568561872909685,\"#A2CF00\"],[0.70903010033444813,\"#A2D000\"],[0.71237458193979941,\"#A1D100\"],[0.71571906354515036,\"#A0D100\"],[0.71906354515050164,\"#9FD200\"],[0.72240802675585292,\"#9FD200\"],[0.72575250836120386,\"#9ED300\"],[0.72909698996655536,\"#9DD300\"],[0.73244147157190631,\"#9CD400\"],[0.73578595317725759,\"#9BD400\"],[0.73913043478260887,\"#9BD500\"],[0.74247491638795982,\"#9AD600\"],[0.7458193979933111,\"#99D600\"],[0.74916387959866237,\"#98D700\"],[0.75250836120401332,\"#97D700\"],[0.7558528428093646,\"#96D800\"],[0.75919732441471577,\"#95D800\"],[0.76254180602006671,\"#94D900\"],[0.76588628762541833,\"#94D900\"],[0.76923076923076927,\"#93DA00\"],[0.77257525083612022,\"#92DB00\"],[0.77591973244147183,\"#91DB00\"],[0.77926421404682278,\"#90DC00\"],[0.78260869565217406,\"#8FDC00\"],[0.78595317725752523,\"#8EDD00\"],[0.78929765886287617,\"#8DDD00\"],[0.79264214046822745,\"#8CDE00\"],[0.79598662207357873,\"#8BDE00\"],[0.79933110367892968,\"#8ADF00\"],[0.80267558528428096,\"#89DF00\"],[0.80602006688963224,\"#88E000\"],[0.80936454849498318,\"#87E100\"],[0.81270903010033446,\"#86E100\"],[0.81605351170568563,\"#85E200\"],[0.81939799331103658,\"#84E200\"],[0.82274247491638819,\"#83E300\"],[0.82608695652173914,\"#82E300\"],[0.82943143812709041,\"#81E400\"],[0.83277591973244169,\"#80E400\"],[0.83612040133779264,\"#7EE500\"],[0.83946488294314392,\"#7DE500\"],[0.84280936454849509,\"#7CE600\"],[0.84615384615384603,\"#7BE700\"],[0.84949832775919731,\"#7AE700\"],[0.85284280936454859,\"#79E800\"],[0.85618729096989954,\"#77E800\"],[0.85953177257525082,\"#76E900\"],[0.8628762541806021,\"#75E900\"],[0.86622073578595304,\"#74EA00\"],[0.86956521739130455,\"#72EA00\"],[0.87290969899665549,\"#71EB00\"],[0.87625418060200677,\"#70EB00\"],[0.87959866220735805,\"#6EEC00\"],[0.882943143812709,\"#6DEC00\"],[0.88628762541806028,\"#6BED00\"],[0.88963210702341156,\"#6AEE00\"],[0.8929765886287625,\"#68EE00\"],[0.89632107023411378,\"#67EF00\"],[0.89966555183946495,\"#65EF00\"],[0.9030100334448159,\"#64F000\"],[0.90635451505016718,\"#62F000\"],[0.90969899665551845,\"#61F100\"],[0.9130434782608694,\"#5FF100\"],[0.91638795986622101,\"#5DF200\"],[0.91973244147157196,\"#5BF200\"],[0.92307692307692324,\"#5AF300\"],[0.92642140468227452,\"#58F300\"],[0.92976588628762535,\"#56F400\"],[0.93311036789297663,\"#54F400\"],[0.93645484949832791,\"#52F500\"],[0.93979933110367886,\"#50F600\"],[0.94314381270903014,\"#4EF600\"],[0.94648829431438142,\"#4BF700\"],[0.94983277591973236,\"#49F700\"],[0.95317725752508364,\"#47F800\"],[0.95652173913043481,\"#44F800\"],[0.95986622073578576,\"#41F900\"],[0.96321070234113737,\"#3FF900\"],[0.96655518394648832,\"#3CFA00\"],[0.96989966555183926,\"#38FA00\"],[0.97324414715719088,\"#35FB00\"],[0.97658862876254182,\"#32FB00\"],[0.9799331103678931,\"#2EFC00\"],[0.98327759197324438,\"#29FC00\"],[0.98662207357859522,\"#24FD00\"],[0.98996655518394649,\"#1FFD00\"],[0.99331103678929777,\"#18FE00\"],[0.99665551839464872,\"#0EFE00\"],[1,\"#00FF00\"]],\"colorbar\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"thickness\":23.039999999999996,\"title\":\"Mean\",\"titlefont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"tickmode\":\"array\",\"ticktext\":[\"400\",\"500\",\"600\",\"700\"],\"tickvals\":[0.039791760977817968,0.32178210351591968,0.60377244605402147,0.88576278859212321],\"tickfont\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"ticklen\":2,\"len\":0.5}},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":43.762557077625573,\"r\":7.3059360730593621,\"b\":28.493150684931511,\"l\":43.105022831050235},\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Mean Math Scores per School\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342465},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[0.40000000000000002,164.59999999999999],\"tickmode\":\"array\",\"ticktext\":[\"70200001\",\"70200002\",\"70200003\",\"70200004\",\"70200005\",\"70200006\",\"70200007\",\"70200008\",\"70200009\",\"70200010\",\"70200011\",\"70200012\",\"70200013\",\"70200014\",\"70200015\",\"70200016\",\"70200017\",\"70200018\",\"70200019\",\"70200020\",\"70200021\",\"70200022\",\"70200023\",\"70200024\",\"70200025\",\"70200026\",\"70200027\",\"70200028\",\"70200029\",\"70200030\",\"70200031\",\"70200032\",\"70200033\",\"70200034\",\"70200035\",\"70200036\",\"70200037\",\"70200038\",\"70200039\",\"70200040\",\"70200041\",\"70200042\",\"70200043\",\"70200044\",\"70200045\",\"70200046\",\"70200047\",\"70200048\",\"70200049\",\"70200050\",\"70200051\",\"70200052\",\"70200053\",\"70200054\",\"70200055\",\"70200056\",\"70200057\",\"70200058\",\"70200059\",\"70200060\",\"70200061\",\"70200062\",\"70200063\",\"70200064\",\"70200065\",\"70200066\",\"70200067\",\"70200068\",\"70200069\",\"70200070\",\"70200071\",\"70200072\",\"70200073\",\"70200074\",\"70200075\",\"70200076\",\"70200077\",\"70200078\",\"70200079\",\"70200080\",\"70200081\",\"70200082\",\"70200083\",\"70200084\",\"70200085\",\"70200086\",\"70200087\",\"70200088\",\"70200089\",\"70200090\",\"70200091\",\"70200092\",\"70200093\",\"70200094\",\"70200095\",\"70200096\",\"70200097\",\"70200098\",\"70200099\",\"70200100\",\"70200101\",\"70200102\",\"70200103\",\"70200104\",\"70200105\",\"70200106\",\"70200107\",\"70200108\",\"70200109\",\"70200110\",\"70200111\",\"70200112\",\"70200113\",\"70200114\",\"70200115\",\"70200116\",\"70200117\",\"70200118\",\"70200119\",\"70200120\",\"70200121\",\"70200122\",\"70200123\",\"70200124\",\"70200125\",\"70200126\",\"70200127\",\"70200128\",\"70200129\",\"70200130\",\"70200131\",\"70200132\",\"70200133\",\"70200134\",\"70200135\",\"70200136\",\"70200137\",\"70200138\",\"70200139\",\"70200140\",\"70200141\",\"70200142\",\"70200143\",\"70200144\",\"70200145\",\"70200146\",\"70200147\",\"70200148\",\"70200149\",\"70200151\",\"70200152\",\"70200153\",\"70200154\",\"70200155\",\"70200156\",\"70200157\",\"70200158\",\"70200159\",\"70200160\",\"70200161\",\"70200162\",\"70200163\",\"70200164\",\"70200165\"],\"tickvals\":[1,2,3,3.9999999999999996,5,6,7,8,9,10,10.999999999999998,12.000000000000002,13,14,15,16,17,18,19,20,21,22,23,24,24.999999999999996,26,27.000000000000004,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44.000000000000007,45,46,47,48,49,50,50.999999999999993,52,53,54,55.000000000000007,56,57,57.999999999999993,59,60,61,62.000000000000007,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85.000000000000014,86,87,88.000000000000014,89,90,90.999999999999986,92,93,94,95,96,97,98,99.000000000000014,100,101,101.99999999999999,103,104,104.99999999999999,106,107,108,109,110.00000000000001,111,112,113.00000000000001,114,115,115.99999999999999,117,118,119,120,121,122,123,124.00000000000001,125,126,126.99999999999999,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164],\"categoryorder\":\"array\",\"categoryarray\":[\"70200001\",\"70200002\",\"70200003\",\"70200004\",\"70200005\",\"70200006\",\"70200007\",\"70200008\",\"70200009\",\"70200010\",\"70200011\",\"70200012\",\"70200013\",\"70200014\",\"70200015\",\"70200016\",\"70200017\",\"70200018\",\"70200019\",\"70200020\",\"70200021\",\"70200022\",\"70200023\",\"70200024\",\"70200025\",\"70200026\",\"70200027\",\"70200028\",\"70200029\",\"70200030\",\"70200031\",\"70200032\",\"70200033\",\"70200034\",\"70200035\",\"70200036\",\"70200037\",\"70200038\",\"70200039\",\"70200040\",\"70200041\",\"70200042\",\"70200043\",\"70200044\",\"70200045\",\"70200046\",\"70200047\",\"70200048\",\"70200049\",\"70200050\",\"70200051\",\"70200052\",\"70200053\",\"70200054\",\"70200055\",\"70200056\",\"70200057\",\"70200058\",\"70200059\",\"70200060\",\"70200061\",\"70200062\",\"70200063\",\"70200064\",\"70200065\",\"70200066\",\"70200067\",\"70200068\",\"70200069\",\"70200070\",\"70200071\",\"70200072\",\"70200073\",\"70200074\",\"70200075\",\"70200076\",\"70200077\",\"70200078\",\"70200079\",\"70200080\",\"70200081\",\"70200082\",\"70200083\",\"70200084\",\"70200085\",\"70200086\",\"70200087\",\"70200088\",\"70200089\",\"70200090\",\"70200091\",\"70200092\",\"70200093\",\"70200094\",\"70200095\",\"70200096\",\"70200097\",\"70200098\",\"70200099\",\"70200100\",\"70200101\",\"70200102\",\"70200103\",\"70200104\",\"70200105\",\"70200106\",\"70200107\",\"70200108\",\"70200109\",\"70200110\",\"70200111\",\"70200112\",\"70200113\",\"70200114\",\"70200115\",\"70200116\",\"70200117\",\"70200118\",\"70200119\",\"70200120\",\"70200121\",\"70200122\",\"70200123\",\"70200124\",\"70200125\",\"70200126\",\"70200127\",\"70200128\",\"70200129\",\"70200130\",\"70200131\",\"70200132\",\"70200133\",\"70200134\",\"70200135\",\"70200136\",\"70200137\",\"70200138\",\"70200139\",\"70200140\",\"70200141\",\"70200142\",\"70200143\",\"70200144\",\"70200145\",\"70200146\",\"70200147\",\"70200148\",\"70200149\",\"70200151\",\"70200152\",\"70200153\",\"70200154\",\"70200155\",\"70200156\",\"70200157\",\"70200158\",\"70200159\",\"70200160\",\"70200161\",\"70200162\",\"70200163\",\"70200164\",\"70200165\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":false,\"tickfont\":{\"color\":null,\"family\":null,\"size\":0},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"School ID\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[355.608,770.79199999999992],\"tickmode\":\"array\",\"ticktext\":[\"400\",\"500\",\"600\",\"700\"],\"tickvals\":[400,500,600,700],\"categoryorder\":\"array\",\"categoryarray\":[\"400\",\"500\",\"600\",\"700\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":false,\"gridcolor\":null,\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Mean Math Scores\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498},\"title\":{\"text\":\"Mean\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"16e478dd3764\":{\"x\":{},\"y\":{},\"colour\":{},\"type\":\"scatter\"},\"16e4410f5fb\":{\"x\":{},\"y\":{},\"label\":{}},\"16e43c5d48f6\":{\"x\":{},\"y\":{},\"label\":{}},\"16e41662d29\":{\"yintercept\":{}},\"16e4219d7813\":{\"yintercept\":{}},\"16e47eaa3cae\":{\"x\":{},\"y\":{},\"label\":{}},\"16e47e3b33f7\":{\"x\":{},\"y\":{},\"label\":{}}},\"cur_data\":\"16e478dd3764\",\"visdat\":{\"16e478dd3764\":[\"function (y) \",\"x\"],\"16e4410f5fb\":[\"function (y) \",\"x\"],\"16e43c5d48f6\":[\"function (y) \",\"x\"],\"16e41662d29\":[\"function (y) \",\"x\"],\"16e4219d7813\":[\"function (y) \",\"x\"],\"16e47eaa3cae\":[\"function (y) \",\"x\"],\"16e47e3b33f7\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n::: callout-note\n## Note\n\nSome of the previous annotations generated in the static plot may not appear after turning it into an interactive plot. Hence, we can use both static and interactive plots together if needed. For example, static charts to quickly summarize and communicate information to reader, and an interactive plot for readers to drill down in more detail, eg use of zoom, identifying specific data points via tooltip etc.\n:::\n\n## 3.3 Distribution of students’ performance in Math, Science and Reading by gender\n\nThe author had used the [`pisa.mean.pv`](https://www.rdocumentation.org/packages/intsvy/versions/2.8/topics/pisa.mean.pv) function from [`intsvy`](https://daniel-caro.com/r-intsvy) package to obtain the Mean and Standard Deviation of PV values from “PV1MATH” to “PV10MATH”, “PV1READ” to “PV10READ” and “PV1SCIE” to “PV10SCIE” for each gender.\n\nThe code below was used to generate the composite PV values for Math, Reading and Science by gender.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npvmathgenderonly <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"MATH\"),c(\"ST004D01T\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvmath_bygenderonly\",folder=data_folder_path)\n\npvreadgenderonly <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"READ\"),c(\"ST004D01T\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvread_bygenderonly\",folder=data_folder_path)\n\npvsciegenderonly <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"SCIE\"),c(\"ST004D01T\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvscie_bygenderonly\",folder=data_folder_path)\n```\n:::\n\n\nA plot to display the distribution of Math, Reading and Science scores by gender was generated using the code below.\n\n::: panel-tabset\n## The Original plot\n\n![](images/clipboard-3304529458.png)\n\nThe author had created a series of error bars across the 3 subjects to represent the subject scores by gender.\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pvmathgenderonly, aes(x = as.factor(ST004D01T), y = Mean,fill=ST004D01T)) +\n  geom_boxplot(width = 0.5, position = position_dodge(width = 0.75),lwd=0.5,show.legend=FALSE) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    shape = 18,\n    size = 5,\n    aes(colour=ST004D01T),\n    position = position_dodge(width = 0.75)) +\n  geom_errorbar(\n    aes(ymin = Mean - SD, ymax = Mean + SD,color=ST004D01T),\n    width = 0.5,\n    size=0.8,\n    position = position_dodge(width = 0.5)\n  ) +\n  labs(title = \"Math Scores by Gender\") +\n  ylab(\"Math Score\") +\n  xlab(\"Gender\")+\n  scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 100))+\n  scale_fill_discrete(name = \"Gender\") +\n  scale_color_discrete(name = \"Gender\") +\n  coord_flip() +\n  theme_gray()\n```\n:::\n\n:::\n\n### 3.3.1 Evaluation\n\n+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Assessment Criteria | Critique/Feedback                                                                                                                                                                                              | Possible Improvements                                                                                                                                                                                   |\n+=====================+================================================================================================================================================================================================================+=========================================================================================================================================================================================================+\n| **Clarity**         | 1.  Although the original plot enables me to see the differences in scores between the genders, I am unclear as to which score this is showing. Is it showing the range of PV1 scores or average of PV values? | 1.  The code and subset used is not suitable to plot a range of scores for each gender across subjects.                                                                                                 |\n|                     |                                                                                                                                                                                                                |                                                                                                                                                                                                         |\n|                     | 2.  Graph is titled as “Subject Scores by Gender”, however the code indicates that mean scores +/- one standard deviation were generated instead.                                                              | 2.  I will extract a new subset with all PV1 scores at the individual student level. This will then be used to plot the distribution and range of scores for the different genders across all subjects. |\n|                     |                                                                                                                                                                                                                |                                                                                                                                                                                                         |\n|                     | 3.  The data subset used for the plot only has 2 observations and 6 variables. Upon inspecting the data set, this subset is actually the composite mean score for each gender across the subjects.             |                                                                                                                                                                                                         |\n+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Aesthetics**      | 1.  The graphs are already well labelled in the x and y axes, and identifies the different genders clearly. The use of different colors per gender together with the legend is not necessary.                  | 1.  To remove the legend since there are only two categories of gender and they are already differentiated by colour.                                                                                   |\n|                     |                                                                                                                                                                                                                |                                                                                                                                                                                                         |\n|                     | 2.  The scale for the X-axis is from 0 to 1000, in increments of 50. Because of the “shortness” of the error bars, the graph appears too elongated.                                                            | 2.  Shorten the X-axis, or extract new data points to correctly populate the range of scores.                                                                                                           |\n|                     |                                                                                                                                                                                                                |                                                                                                                                                                                                         |\n|                     | 3.  Unable to decipher the actual scores even with the granularity in X-axis tick marks.                                                                                                                       | 3.  To annotate the mean scores onto the plot, so that we can remove the background grid lines and X-axis tick marks and reduce non-data ink.                                                           |\n|                     |                                                                                                                                                                                                                |                                                                                                                                                                                                         |\n|                     |                                                                                                                                                                                                                | 4.  The new visualization will need to enable readers to quickly differentiate the performance between genders across subjects.                                                                         |\n+---------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n::: callout-note\n## Observation\n\nupon closer examination of the code below, the author had included an error bar with Mean +/- one standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#geom_errorbar(\n    #aes(ymin = Mean - SD, ymax = Mean + SD,color=ST004D01T),\n    #width = 0.5,\n    #size=0.8,\n    #position = position_dodge(width = 0.5)\n```\n:::\n\n\nThe original data set and plot is instead comparing the mean subject scores across different genders.\n:::\n\nExamining the subset used for the original plot in more detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(pvmathgenderonly)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ST004D01T Freq   Mean s.e.     SD  s.e\n1    Female 3227 569.01 1.70  97.49 1.14\n2      Male 3332 581.30 1.74 107.09 1.36\n```\n\n\n:::\n:::\n\n\nThe *pvmathgenderonly* data set only has 2 observations and 6 variables.\n\n::: callout-note\n## Conclusion\n\nThis data set can only be used to compare the overall mean scores for genders across the 3 subjects.\n\nThe visualization needs to be done differently to enable the reader to obtain more information regarding the performance between genders.\n\nI will extract a new subset and create new graphs to show the range and distribution of scores between the genders across subjects.\n\nI will use PV1 scores which are available for all students to create new plots to visualize the distribution of scores.\n:::\n\n### 3.3.2 Sketch of Proposed Design\n\nRough sketch of proposed design is shown below.\n\n![](images/clipboard-800776571.png)\n\n### 3.3.3 Remake\n\nThe original data subset and plot is unable to exhibit the range and distribution of subject scores across genders, due to the lack of scores at an individual student level.\n\nTherefore, I will extract data from the original data set to create new subsets for the new plots using the code below.\n\nIn terms of data, I will use the PV1 scores which are available for all students.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Create a subset of the data with gender and PV1 score columns\nsubset_gender_PV1 <- stu_qqq_SG %>%\n  select(ST004D01T, PV1MATH, PV1SCIE, PV1READ)\n\n# Convert the \"ST004D01T\" column to a factor \nsubset_gender_PV1$ST004D01T <- factor(subset_gender_PV1$ST004D01T, levels = c(1, 2), labels = c(\"Female\", \"Male\"))\n\nMath_gender <- subset_gender_PV1 %>%\n  group_by(ST004D01T) %>%  # Group by gender column\n  summarise(\n    Freq = n(),             # Count the frequency of each gender\n    Mean = mean(PV1MATH, na.rm = TRUE)  # Calculate the mean of PV1MATH, removing NA values\n  )\n\nRead_gender <- subset_gender_PV1 %>%\n  group_by(ST004D01T) %>%  # Group by gender column\n  summarise(\n    Freq = n(),             # Count the frequency of each gender\n    Mean = mean(PV1READ, na.rm = TRUE)  # Calculate the mean of PV1READ, removing NA values\n  )\n\nSCIE_gender <- subset_gender_PV1 %>%\n  group_by(ST004D01T) %>%  # Group by gender column\n  summarise(\n    Freq = n(),             # Count the frequency of each gender\n    Mean = mean(PV1SCIE, na.rm = TRUE)  # Calculate the mean of PV1SCIE, removing NA values\n  )\n```\n:::\n\n\nNext, I will use the code below to create new box plots for each subject. This will show the range of scores for the genders in different subjects.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Create the plot using the subset_data\nbxp1 <- ggplot(subset_gender_PV1, aes(x = ST004D01T, y = PV1MATH, fill = ST004D01T)) +\n  geom_boxplot() +\n  coord_cartesian(ylim = c(0, 1000)) +\n  geom_point(data = Math_gender, aes(x = ST004D01T, y = Mean), color = \"blue\", size = 1.5) +\n  geom_text(data = Math_gender, \n          aes(x = ST004D01T, y = Mean, label = paste(\"Mean:\", round(Mean, 2))), \n          color = \"black\", hjust = -0.2, vjust =4, size = 2.75) +\n  labs(x = \"Gender\",\n       y = \"Math Scores\") +\n  scale_fill_manual(values = c(\"Female\" = \"lightblue\", \"Male\" = \"lightblue\")) +  \n  theme_minimal() +\n  theme(legend.position = \"none\") \n\n\nbxp2 <- ggplot(subset_gender_PV1, aes(x = ST004D01T, y = PV1READ, fill = ST004D01T)) +\n  geom_boxplot() +\n  coord_cartesian(ylim = c(0, 1000)) +\n  geom_point(data = Read_gender, aes(x = ST004D01T, y = Mean), color = \"blue\", size = 1.5) +\n  geom_text(data = Math_gender, \n          aes(x = ST004D01T, y = Mean, label = paste(\"Mean:\", round(Mean, 2))), \n          color = \"black\", hjust = -0.2, vjust = 4.25, size = 2.75) +\n  labs(x = \"Gender\",\n       y = \"Reading Scores\") +\n  scale_fill_manual(values = c(\"lightgreen\", \"lightgreen\")) +  # Associate colors with factor levels\n  theme_minimal() +\n  theme(legend.position = \"none\") \n  \n\nbxp3 <- ggplot(subset_gender_PV1, aes(x = ST004D01T, y = PV1SCIE, fill = ST004D01T)) +\n  geom_boxplot() +\n  coord_cartesian(ylim = c(0, 1000)) +\n  geom_point(data = SCIE_gender, aes(x = ST004D01T, y = Mean), color = \"blue\", size = 1.5) +\n  geom_text(data = Math_gender, \n          aes(x = ST004D01T, y = Mean, label = paste(\"Mean:\", round(Mean, 2))), \n          color = \"black\", hjust = -0.2, vjust = 4, size = 2.75) +\n  labs(x = \"Gender\",\n       y = \"Science Scores\") +\n  scale_fill_manual(values = c(\"lightpink\", \"lightpink\")) +  # Associate colors with factor levels\n  theme_minimal() +\n  theme(legend.position = \"none\") \n```\n:::\n\n\nBesides showing the differences in scores through box plots, I will also plot ridgeline plots, segmented into 4 quantiles, to display the distribution and difference in subject scores between genders across the subjects.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nrp1 <- ggplot(subset_gender_PV1,\n       aes(x = PV1MATH, \n           y = ST004D01T, \n           fill = factor(stat(quantile))\n           )) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = 4,\n    quantile_lines = TRUE) +\n  scale_fill_viridis_d(name = \"Quartiles\") +\n  scale_x_continuous(\n    name = NULL,\n    expand = c(0, 0)\n    ) +\n  scale_y_discrete(name = NULL, expand = expansion(add = c(0.2, 2.6))) +\n  theme_ridges() +\n  theme(legend.position = \"none\",\n        plot.title = element_text(size = 10)  \n  )  +\n  labs(title = \"Math Scores\\nacross genders\")\n\nrp2 <- ggplot(subset_gender_PV1,\n       aes(x = PV1READ, \n           y = ST004D01T, \n           fill = factor(stat(quantile))\n           )) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = 4,\n    quantile_lines = TRUE) +\n  scale_fill_viridis_d(name = \"Quartiles\") +\n  scale_x_continuous(\n    name = NULL,\n    expand = c(0, 0)\n    ) +\n  scale_y_discrete(name = NULL, expand = expansion(add = c(0.2, 2.6))) +\n  theme_ridges() +\n  theme(legend.position = \"none\",\n        plot.title = element_text(size = 10)  \n  )  +\n  labs(title = \"Reading Scores \\nacross genders\")\n\nrp3 <- ggplot(subset_gender_PV1,\n       aes(x = PV1SCIE, \n           y = ST004D01T, \n           fill = factor(stat(quantile))\n           )) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = 4,\n    quantile_lines = TRUE,\n    alpha = 0.5 ) +\n  scale_fill_viridis_d(name = \"Quartiles\") +\n  scale_x_continuous(\n    name = NULL,\n    expand = c(0, 0)\n    ) +\n  scale_y_discrete(name = NULL, expand = expansion(add = c(0.2, 2.6))) +\n  theme_ridges() +\n  theme(legend.position = \"none\",\n        plot.title = element_text(size = 10)  \n  ) +\n  labs(title = \"Science Scores\\nacross genders\")\n```\n:::\n\n\nI will use the code below to create a composite graph.\n\n\n::: {.cell .column-body-outset-right}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npatch3 <- (rp1+ bxp1)/(rp2+bxp2)/(rp3+bxp3) + \n              plot_annotation(\n                title = \"Male students outperform in Maths and Science\",\n                subtitle = \"Female students outperform in Reading\")\n\npatch3 & theme(panel.grid.major = element_blank(),)\n```\n\n::: {.cell-output-display}\n![](R_Ex3_files/figure-html/unnamed-chunk-27-1.png){width=768}\n:::\n:::\n\n\n::: callout-tip\n## Revised Plot\n\nThe revised plot consists of a patchwork of ridgeline plots and box plots for each subject.\n\nThe ridgeline plot been further segmented into 4 quantiles, differentiated by colour. This not only provides insights into the distribution of the scores but also enables readers to quickly understand the differences in performance between genders.\n\nThe box plots, further help readers to understand the differences in scores between genders. The range of scores can be seen along with the mean scores.\n:::\n\n## 3.4 Distribution of Math, Reading and Science scores by socioeconomic status\n\nThe author had previously created a new variable, “ESCS_recoded”, which bins the socio-economic (ESCS) score into four quantiles - “Very Low”, “Low”, “Medium” and “High”. The author had used the [`pisa.mean.pv`](https://www.rdocumentation.org/packages/intsvy/versions/2.8/topics/pisa.mean.pv) function from [`intsvy`](https://daniel-caro.com/r-intsvy)`package` to obtain the Mean and Standard Deviation of PV values from “PV1MATH” to “PV10MATH”, “PV1READ” to “PV10READ” and “PV1SCIE” to “PV10SCIE” and grouped by the ESCS score.\n\nThe code below was used to generate the composite PV values for Math, Reading and Science.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npvmathescs <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"MATH\"),c(\"ESCS_recoded\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvmathescs\",folder=data_folder_path)\n\npvreadescs <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"READ\"),c(\"ESCS_recoded\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvreadescs\",folder=data_folder_path)\n\npvscieescs <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"SCIE\"),c(\"ESCS_recoded\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvscieescs\",folder=data_folder_path)\n```\n:::\n\n\nA plot to display the distribution of Math, Reading and Science scores across schools by socioeconomic status was generated using the code below.\n\n::: panel-tabset\n## The Original plot\n\n![](images/clipboard-1075189504.png)\n\nThe author had created a series of error bars to represent the scores across the 4 categories of the ESCS score (High, Medium, Low, Very Low).\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pvscieescs, aes(x = ESCS_recoded, y = Mean,fill=ESCS_recoded))+\n  geom_boxplot(width = 0.5, position = position_dodge(width = 0.5),lwd=0.5,show.legend=FALSE) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    shape = 10,\n    size = 2,\n    aes(colour=ESCS_recoded),\n    position = position_dodge(width = 0.75)) +\n  geom_errorbar(\n    aes(ymin = Mean - SD, ymax = Mean + SD,color=ESCS_recoded),\n    width = 0.5,\n    size=1,\n    position = position_dodge(width = 0.5)\n  ) +\n  labs(title = \"Science Scores by Socioeconomic Status\") +\n  ylab(\"Science Score\") +\n  xlab(\"Socioeconomic Status\")+\n  scale_y_continuous(limits=c(0,1000),breaks = seq(0, 1000, by=200))+\n  coord_flip() +\n  theme_minimal(base_size=10)\n```\n:::\n\n:::\n\n### 3.4.1 Evaluation\n\n+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Assessment Criteria | Critique/Feedback                                                                                                                                                                                                               | Possible Improvements                                                                                                                                                                                                                                |\n+=====================+=================================================================================================================================================================================================================================+======================================================================================================================================================================================================================================================+\n| **Clarity**         | 1.  Although the original plot enables me to visualize the differences in scores between the ESCS categories, I am unclear as to which score this is showing. Is it showing me the range of PV1 scores or average of PV values? | 1.  The code and subset used is not suitable to plot a range or distribution of scores for each ESCS score category.                                                                                                                                 |\n|                     |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                      |\n|                     | 2.  Graph is titled as “Subject Scores by Socioeconomic Status”, however the code indicates that mean scores +/- one standard deviation were generated instead.                                                                 | 2.  I will extract a new subset with all PV1 scores at the individual student level together with ESCS scores per student. I will then plot the relationship between the two continuous variables (subject scores and ESCS score) via scatter plots. |\n|                     |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                      |\n|                     | 3.  The data subset used for the plots only has 4 observations and 6 variables. Upon inspecting the data set, this is actually just the overall mean scores for each of the newly binned ESCS score category.                   | 3.  A scatter plots will enable readers to quickly infer the relationships between subject scores and socioeconomic statuses.                                                                                                                        |\n+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Aesthetics**      | 1.  The Y-axis is already well labelled and identifies the different socioeconomic segments clearly, the use of different colors per segment together with legend is not necessary.                                             | 1.  To remove the legend since the ESCS segments are already differentiated by colour and identifiable through the Y-axis labels.                                                                                                                    |\n|                     |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                      |\n|                     | 2.  The scale for the X-axis is from 0 to 1000, in increments of 50. Because of the “shortness” of the error bars, the graph appears too elongated.                                                                             | 2.  Shorten the X-axis, or extract new data points to correctly populate the range of scores.                                                                                                                                                        |\n|                     |                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                      |\n|                     | 3.  Even with the background grid lines and X axis tick marks, I am unable to decipher the actual scores clearly.                                                                                                               | 3.  To annotate the mean scores onto the plot, so that we can remove the background grid lines and X-axis tick marks and reduce non-data ink.                                                                                                        |\n+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n::: callout-note\n## Observation\n\nUpon closer examination of the code below, the author had included an error bar with Mean +/- one standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#geom_errorbar(\n    #aes(ymin = Mean - SD, ymax = Mean + SD,color=ESCS_recoded),\n    #width = 0.5,\n    #size=1,\n    #position = position_dodge(width = 0.5)\n```\n:::\n\n\nHence the original plot can only be used to compare the mean subject scores across different ESCS segments.\n:::\n\nExamining the subset used for the original plot in more detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(pvscieescs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ESCS_recoded Freq   Mean s.e.    SD  s.e\n1     Very Low 1640 503.73 3.14 97.91 1.97\n2          Low 1640 546.33 2.61 93.23 1.75\n3       Medium 1640 584.61 2.31 86.07 2.04\n4         High 1639 610.62 3.23 84.01 2.21\n```\n\n\n:::\n:::\n\n\nThe data subset used for the plots only has 4 observations and 6 variables.\n\n::: callout-note\n## Conclusion\n\nThis subset and the code used is not able to plot the range of scores per ESCS segment, and can only be used to compare the composite mean scores of each of the 4 ESCS segments.\n\nAlthough it is useful to compare the mean scores between different ESCS segments, a different set of data and plots can be used instead to communicate more information about the strength or weakness of the relationship between subject scores and socioeconomic statuses.\n:::\n\nAdditionally, the **binning** of the ESCS score, while helpful may be limited in usefulness, for the following reasons:-\n\n-   Binning the ESCS scores adds in an element of subjectivity. For example, why should there be 4 segments of socioeconomic statuses instead of 3, or 6?\n\n-   Could the number of socioeconomic segments be applicable for other countries? For example, would a \"Low segment\" in Singapore be equivalent to a \"Low segment\" in another country?\n\n### 3.4.2 Sketch of Proposed Design\n\nRough sketch of proposed design is shown below.\n\n![](images/clipboard-3423147912.png)\n\n### 3.4.4 Remake\n\nInstead of binning the ESCS score and transforming it to a categorical type, I will keep the ESCS score as a continuous variable.\n\nI will use scatter plots to visualize the strength or weaknesses of the relationships between the socioeconomic statuses and subject scores.\n\nDrawing inspiration from Prof Kam's [Lesson 3](https://isss608-ay2023-24jan.netlify.app/outline/lesson03_outline) and well as additional useful references, I will proceed to plot [Scatter plots with Marginal Histograms.](https://things-about-r.tumblr.com/post/124004085689/scatter-plots-with-marginal-densities-an-example)\n\nIn terms of data, I will use the PV1 scores which at the individual student level.\n\nFor this visualization, I will use the [ggstatplot package](https://cran.r-project.org/web/packages/ggstatsplot/index.html). [@patil2021]\n\nFor more information on this package and how it can be used to create graphics from statistical tests included in the plots themselves, please [refer to this link.](https://joss.theoj.org/papers/10.21105/joss.03167)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggstatsplot)\n```\n:::\n\n\nCreating new data subset for visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsubset_ESCS_PV1 <- stu_qqq_SG %>%\n  select(ESCS, PV1MATH, PV1SCIE, PV1READ)\n\n#omiting NA values\nsubset_ESCS_PV1 <- na.omit(subset_ESCS_PV1)\n```\n:::\n\n\nWe will use the code below from `ggstatplot package` to generate the plot.\n\n\n::: {.cell .column-body-outset-right}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nggscatterstats(\n  data = subset_ESCS_PV1,                                          \n  x = ESCS,                                                  \n  y = PV1MATH,\n  xlab = \"Socioeconomic score (ESCS)\",\n  ylab = \"Math scores\",\n  marginal = TRUE,\n  marginal.type = \"histogram\",\n  centrality.para = \"mean\",\n  margins = \"both\",\n  title = \"Relationship between Socio-economic and Math scores\",\n  messages = FALSE\n)\n```\n\n::: {.cell-output-display}\n![](R_Ex3_files/figure-html/unnamed-chunk-34-1.png){width=768}\n:::\n:::\n\n\n::: callout-tip\n## Revised Plot\n\nThe benefit of this plot is that it shows both the correlation between the two continous variables as well as their respective distributions, and includes important statistics like the Pearson coefficient.\n\nFrom the plot above, the pearson coefficient of 0.42 indicates that there is a weak positive relationship between ESCS scores and Math scores.\n\nThe marginal histograms for both variables also enables readers to additionally infer the distribution of these variables. For example, Math scores resemble a normal distribution, while ESCS scores resemble a left-skewed distribution.\n:::\n\n## 3.5 Distribution of students’ performance in Math, Science and Reading by gender across schools\n\nThe author had intended to analyse whether there are differences in performances in Math, Reading and Science between genders at a more granular level - within schools.\n\nThe author had used the [`pisa.mean.pv`](https://www.rdocumentation.org/packages/intsvy/versions/2.8/topics/pisa.mean.pv) function from [`intsvy`](https://daniel-caro.com/r-intsvy)`package` to obtain the Mean and Standard Deviation of PV values from “PV1MATH” to “PV10MATH”, “PV1READ” to “PV10READ” and “PV1SCIE” to “PV10SCIE” for each school and by gender.\n\nThe below code was used to generate the composite PV values.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\npvmathgender <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"MATH\"),c(\"CNTSCHID\",\"ST004D01T\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvmath_bygender\",folder=data_folder_path)\n\npvreadgender <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"READ\"),c(\"CNTSCHID\",\"ST004D01T\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvread_bygender\",folder=data_folder_path)\n\npvsciegender <- pisa.mean.pv(pvlabel=paste0(\"PV\",1:10,\"SCIE\"),by= c(\"CNTSCHID\",\"ST004D01T\"), data=stu_qqq_SG_clean,export=FALSE,name=\"pvscie_bygender\",folder=data_folder_path)\n```\n:::\n\n\nA plot to display the distribution of Math, Reading and Science scores across schools by gender, was generated using the code below.\n\n::: panel-tabset\n## The Original Plot\n\n![](images/clipboard-2922052911.png)\n\nThe author had created a series of 2 error bars for each school ID across the 3 subjects to represent the subject scores for each gender for all schools (164 schools).\n\n## The code\n\n\n::: {.cell}\n\n```{.r .cell-code}\np8<- ggplot(pvmathgender, aes(x = as.factor(CNTSCHID), y = Mean,fill=ST004D01T))+\n  geom_boxplot(width = 0.5, position = position_dodge(width = 0.75),lwd=1.5,show.legend=FALSE) +\n  stat_summary(\n    fun = mean,\n    geom = \"point\",\n    shape = 18,\n    size = 10,\n    aes(colour=ST004D01T),\n    position = position_dodge(width = 0.75)) +\n  geom_errorbar(\n    aes(ymin = Mean - SD, ymax = Mean + SD,color=ST004D01T),\n    width = 1,\n    size=2,\n    position = position_dodge(width = 0.5)\n  ) +\n  labs(title = \"Math Scores by Gender across Schools\") +\n  ylab(\"Math Score\") +\n  xlab(\"School ID\")+\n  scale_y_continuous(limits=c(0,1000),breaks = seq(0, 1000, by=200))+\n  coord_flip() +\n  theme_minimal(base_size=50)+\n  theme(legend.position=\"none\")\n```\n:::\n\n:::\n\n### 3.5.1 Evaluation\n\n+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| Assessment Criteria | Critique/Feedback                                                                                                                                                                                                                                                               | Possible Improvements                                                                                                                                                                                                  |\n+=====================+=================================================================================================================================================================================================================================================================================+========================================================================================================================================================================================================================+\n| **Clarity**         | 1.  Although the original plot enables me to visualize the differences in scores across schools, I am unclear as to which score this is showing. Is it showing me the range of gender scores by school ID?                                                                      | 1.  Previous visualization had already analysed the differences per school. To further make it more granular by introducing gender, does not seem to add further value in terms of insights.                           |\n|                     |                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                        |\n|                     | 2.  Graph is titled as “Subject Scores by Gender across school\", however the code indicates that mean scores +/- one standard deviation were generated instead.                                                                                                                 | 2.  We can retain the original intent to show the granular difference in performance for the schools, by examining the actual disparity between the best and the worst schools instead.                                |\n|                     |                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                        |\n|                     | 3.  The data subset used for this visualization has 301 observations and 7 variables. Upon inspecting the data set, it is basically the overall mean subject scores for male and female students per school                                                                     |                                                                                                                                                                                                                        |\n+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Aesthetics**      | 1.  The use of a vertically long plot to compare the scores across schools makes it visually challenging and difficult to spot differences between schools, and identify any clusters.                                                                                          | 1.  To revise the design of a vertically long format and re-make it to a horizontally compact visualization, by using ridge line plots to show the differences in performance only between the best and worst schools. |\n|                     |                                                                                                                                                                                                                                                                                 | 2.  To minimize axis labels, we will only identify and plot the top & bottom 5 schools instead.                                                                                                                        |\n|                     | 2.  Since there are 164 schools, the use of a vertically long format makes it difficult to read the Y-axis labels. There are too many schools to make identification off the Y-axis easy. This is further compounded with the additional splitting of genders for every school. |                                                                                                                                                                                                                        |\n|                     |                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                        |\n|                     | 3.  The distance between the X-axis, which shows the scores is too far apart from the error bars. I am unable to decipher what are the actual scores or score range for each error bar.                                                                                         |                                                                                                                                                                                                                        |\n|                     |                                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                        |\n|                     | 4.  The graph is patched side by side, resulting in the Y-axis being repeated 3 times. The order of the School IDs are all the same, hence this creates additional non-data ink, that makes the graph too “busy”.                                                               |                                                                                                                                                                                                                        |\n+---------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\nExamining the subset used for the original plot in more detail.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(head(pvmathgender))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  CNTSCHID ST004D01T Freq   Mean  s.e.    SD   s.e\n1 70200001      Male   55 725.21  9.34 59.23  6.38\n2 70200002    Female   15 537.70 27.07 80.64 15.79\n3 70200002      Male   22 535.13 21.92 96.03 20.81\n4 70200003    Female    7 739.65 22.04 39.42 14.39\n5 70200003      Male   29 739.99 14.58 62.67  8.56\n6 70200004    Female   28 505.32 19.68 91.11 11.94\n```\n\n\n:::\n:::\n\n\nThe *pvmathgender* subset table has 307 observations and 7 variables.\n\n::: callout-note\n## Conclusion\n\nThe data subset can only be used to visualize the mean scores of the two genders for every school.\n\nThe original graph is not of a suitable design to help readers easily and quickly understand the disparity in performances between schools. By adding a further split into genders per school further complicates this visually.\n\nI will use a new compact visualization to enable the reader to quickly identify the disparity in school performance. Instead of analyzing all schools, we can narrow our focus just to the \"best\" and \"worst\" schools.\n:::\n\n### 3.5.2 Sketch of Proposed Design\n\nRough sketch of proposed design is shown below.\n\n![](images/clipboard-2581295591.png)\n\n### 3.5.3 Remake\n\nThe author had previously extracted the mean scores per school across the 3 subjects. I will use the same sub sets to extract the top and bottom 5 School IDs for each subject.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Identify the top and bottom 5 schools\ntop_bottom_math <- pvmathsch %>%\n  arrange(Mean) %>%\n  slice(c(1:5, (n()-4):n())) %>%\n  pull(CNTSCHID)\n\ntop_bottom_read <- pvreadsch %>%\n  arrange(Mean) %>%\n  slice(c(1:5, (n()-4):n())) %>%\n  pull(CNTSCHID)\n\ntop_bottom_scie <- pvsciesch %>%\n  arrange(Mean) %>%\n  slice(c(1:5, (n()-4):n())) %>%\n  pull(CNTSCHID)\n```\n:::\n\n\nNext I will filter the data set and obtain PV1 student scores from the top and bottom 5 schools only.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Filter the original dataset to include only the selected schools\n\ntop_bottom_mathsch <- stu_qqq_SG %>%\n  filter(CNTSCHID %in% top_bottom_math)\n\ntop_bottom_readsch <- stu_qqq_SG %>%\n  filter(CNTSCHID %in% top_bottom_read)\n\ntop_bottom_sciesch <- stu_qqq_SG %>%\n  filter(CNTSCHID %in% top_bottom_scie)\n\n\ntop_bottom_mathsch <- top_bottom_mathsch %>%\n  mutate(CNTSCHID = factor(CNTSCHID, levels = top_bottom_math))\n```\n:::\n\n\nLastly, I will use the code below to create Ridgeline plots for the top and bottom 5 schools.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nmath_5 <- ggplot(top_bottom_mathsch, aes(x = PV1MATH, y = factor(CNTSCHID), fill = after_stat(x))) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = 4,\n    quantile_lines = TRUE) +\n  scale_fill_gradientn(\n    name = \"Math Scores\",\n    colors = c(\"red\", \"green\"),\n    limits = c(min(top_bottom_mathsch$PV1MATH, na.rm = TRUE), max(top_bottom_mathsch$PV1MATH, na.rm = TRUE)),\n    breaks = seq(min(top_bottom_mathsch$PV1MATH, na.rm = TRUE), max(top_bottom_mathsch$PV1MATH, na.rm = TRUE), length.out = 5)\n  ) +\n  coord_cartesian(xlim=c(0,1000)) +\n  theme_ridges() +\n  theme(legend.position = \"none\",\n        plot.title = element_text(size = 15)  \n  )  +\n  labs(y = \"School ID\", x = NULL, title = \"Math Scores for the Top and Bottom 5 Schools\") +\n  theme(\n    axis.text.y = element_text(angle = 0, hjust = 0.5)  \n  )\n\n\nmath_5\n```\n\n::: {.cell-output-display}\n![](R_Ex3_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n::: callout-tip\n## Revised plot\n\nBy narrowing our focus to compare only the top and bottom 5 schools, we are able to clearly infer the actual difference between the \"best\" and \"worst\" schools.\n\nThe new revised plot is now more visually compact, and allows readers to quickly examine the difference in performance between the top and bottom 5 schools.\n:::\n\nBesides this, we can also examine the differences in performance between Male and Female students in these top and bottom 5 schools, using the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Convert ST004D01T to a factor with more meaningful level names\ntop_bottom_mathsch$ST004D01T <- factor(top_bottom_mathsch$ST004D01T, levels = c(1, 2), labels = c(\"Girls\", \"Boys\"))\n\n# Plot\nmath_gender_ridges <- ggplot(top_bottom_mathsch, \n                             aes(x = PV1MATH, \n                                 y = interaction(CNTSCHID, ST004D01T),  # Create interaction between school ID and gender\n                                 fill = after_stat(x))) +\n  stat_density_ridges(\n    geom = \"density_ridges_gradient\",\n    calc_ecdf = TRUE, \n    quantiles = 4,\n    quantile_lines = TRUE\n  ) +\n  scale_fill_gradientn(\n    name = \"Math Scores\",\n    colors = c(\"red\", \"green\"),\n    limits = c(min(top_bottom_mathsch$PV1MATH, na.rm = TRUE), max(top_bottom_mathsch$PV1MATH, na.rm = TRUE)),\n    breaks = seq(min(top_bottom_mathsch$PV1MATH, na.rm = TRUE), max(top_bottom_mathsch$PV1MATH, na.rm = TRUE), length.out = 5)\n  ) +\n  coord_cartesian(xlim = c(0, 1000)) +\n  theme_ridges() +\n  labs(y = \"School ID and Gender\", x = \"Math Scores\", title = \"Math Scores for the Top and Bottom 5 Schools by Gender\") +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(size = 15),\n    axis.text.y = element_text(angle = 0, hjust = 0.5)  \n  )\n\nmath_gender_ridges\n```\n\n::: {.cell-output-display}\n![](R_Ex3_files/figure-html/unnamed-chunk-41-1.png){width=960}\n:::\n:::\n\n\n::: callout-note\n## Note\n\nSchool IDs 70200001, 70200139 and 70200110 does not have any data on Female students and are likely a single-gender school.\n:::\n\n# 4. Learning Points\n\nTake-home exercise 2 serves as an extension for take-home exercise 1 and has provided me with an opportunity to reflect on what I have done for take-home exercise 1.\n\nBelow are my key takeaways for this assignment:\n\n1.  **Underlying data is crucial**\n\nIt is important to understand the underlying data or data set used for the visualization, in order to better understand the design choices behind the visualizations.\n\nFor example, in this case, the author had decided to extract composite PV scores instead of utilizing PV1 scores or the average of the PV scores. This decision had limited the author's ability to create more infomative visualizations due to the smaller data set.\n\n2.  **Less is more**\n\nAs long as the visualization is clear, and enables the reader to obtain information clearly and quickly, it is a good data visualization.\n\nRather than striving to pack as much information within a composite plot, it is important to understand how much time and \"bandwidth\" readers actually have.\n\nFor example, combining multiple complex plots at the same time may confuse readers instead of enlightening them.\n\nStatic visualizations come with their own limitations. Understanding these limits are important to design good visuals which are easily understood by readers.\n\nLabels, annotations and legends serve to inform, but also increases duplicity. Instead of worrying whether there are enough labels to explain and guide readers, it is better to focus on how easy the reader can obtain that information.\n\n3.  **What is the information you want to communicate?**\n\nIt is important to understand the purpose, intent and effect of the visualization. If we are confused about what we want to communicate, readers will feel the same way as well.\n\n4.  **Learning from Peers**\n\nReferencing classmates’ works have given me new perspectives, ideas and best practices on how to approach the same problems. I have also learnt a lot in terms of efficient coding and short cuts. Being able to organically learn in this matter is beneficial, and allows us to retain the knowledge for longer, compared to using shortcuts like Uncle Google or Chat GPT.\n",
    "supporting": [
      "R_Ex3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}