---
title: "Assess and discuss how the role of financial regulators has evolved"
author: "Imran Ibrahim"
date: August 24, 2024
date-modified: "last-modified"
toc: true
execute: 
  eval: true
  echo: true
  freeze: true
  warning: false
  message: false
---

# Assignment Topic

Assess and discuss how the role of financial regulators has evolved, as we now have both incumbent banks and fintech businesses providing the same financial services to the masses.

Make good use of examples, statistics and events to augment and develop your discussion.

## Introduction

Utilizing their expertise in new technologies, adopting innovative business models, and unencumbered with the same magnitude of regulation as banks; fintech businesses have flourished globally and introduced important solutions in payments, P2P lending, crowdfunding, consumer credit, insurance, online trading, and cryptocurrencies services.

As regulators adapt to these new types of financial firms and services, new concerns emerge including consumer protection, clarity and consistency of regulations, regulatory arbitrage, concentration risk and contagion, adequacy of existing financial safeguards, and threats to financial stability.

## The changing role of financial regulators

Financial regulators have had to balance between promoting innovation and fair competition, safeguard their financial systems, protect consumers; while also monitoring for illicit activities, and non- compliance to rules. In some economies, fintech growth was driven by an unmet demand for financial services, while in others, growth was driven by the high cost of financial services and the lack of competition. Although fintech has helped make the financial system become more inclusive and efficient, market failures and systematic risks remain relevant, and may substantially become worse if left unchecked.

Financial regulators have had to keep up with technology trends and anticipate their impact on financial stability. With tech companies becoming more involved in financial services, and with banks deploying new technologies and business models to stay competitive, regulators have had to engage both sides of the divide to understand new technologies and their impact to the financial system. Regulators must now additionally ensure that their policies and regulations can be applied fairly between these two segments to prevent any side from having an advantage over the other.

The role of financial regulators has evolved from merely being a supervisory body to being a progressive entity, actively initiating programs to engage innovative businesses and encourage financial innovation. Regulators like MAS and FCA provide regulatory advice and support, and construct testbeds or environments to actively test new financial products and services. By implementing these initiatives and becoming driving forces in these projects, they enable both banks and fintech firms to grow organically within the stipulated rules, bringing benefit to both their financial system and consumers.

For example, in Singapore, the MAS has initiatives in place to foster fintech collaboration such as fintech offices, accelerator programs and sandbox environments where fintech firms and financial institutions can come together to experiment on innovative products and solutions within a live environment \[1\]. The sandbox environment enables fintech firms and start-ups to test their concepts and technology in a live environment with limited impact to the financial system, thus enabling a viable assessment of their products before launch.

Fintech sandboxes aim to:

1\) Target new business models or technologies

2\) Provide an environment for testing and understanding new technology and methodologies

3\) Encompass specific objectives to resolve existing market frictions

4\) Provide a safe production environment to evaluate real-world results

With the entry of new financial products and fintech firms, regulators have also had to step up their capabilities in monitoring firms and their activities; and to understand the impact of these new products on the financial system and on consumers. To this end, regulators have had to bring in suitable talent, upgrade their technologies and methodologies to keep pace with new financial trends.

RegTech provides technology to help manage regulatory processes within the financial industry. It refers to technology companies that provide technological solutions to help financial firms and regulators. Regulators globally have begun to engage RegTech companies to revamp their IT systems and processes. Functionalities include tools to match large volumes of data to decision rules, automating compliance or oversight processes and real-time monitoring of credit flows in the financial system.  

In a survey of global regulators by the World bank in 2019 \[2\], the top technologies employed by regulators include Machine Learning, Blockchain/DLT, Natural Language Processing, APIs, Cloud computing, Robotic Process Automation and Biometrics. It is interesting to note that regulators have evolved from being mere users of technology and legacy systems to actively deploying new fields of technology to find new applications and usage and keep up with new trends.  In the process, they fortify their capabilities to detect and anticipate any potential adverse impact to their financial systems.

While the objectives of regulators are clear, the implementation of policies in the face of new technologies and financial firms can be challenging. According a 2019 report from the World Bank \[2\] regulators from 111 jurisdictions cited their top four impediments to effective supervision as:

1\) limited technical expertise

2\) limited funding and resources,

3\) unclear or limited jurisdiction over the activity; and

4\) coordinating multiple regulators to enforce regulations.

## Challenges in implementation and adapting to trends

Many Fintech firms operate borderless businesses which blur international jurisdictions. These firms extend their services globally, causing complex transaction monitoring for local regulators. For example, until recently, Binance, the world’s largest crypto exchange did not have an official headquarters. Similarly, big tech firms like Google, Apple and Amazon extend their services globally across multiple jurisdictions. The issue is exacerbated as some of these companies are outside the regulator’s jurisdiction. Regulation may not be uniformed across borders, hence making it difficult to formulate effective policies with other regulators.

Another challenge is the trend of bypassing traditional intermediaries. Different industry players like technology and telecommunications firms have emerged on the scene, providing financial services direct to consumers without collaborating with incumbent financial institutions. These companies may fall under the mandate of different regulators and this calls into question on whether there is a sufficient level of coordination and communication between regulatory bodies to be able to implement effective regulation. For example, in Singapore, Singtel, a telecommunications firm and Grab, a ride-hailing provider both provide payment services by means of a mobile e-wallet.

In Singapore, MAS has issued licenses to 4 digital banks\[3\] which include non-bank entities like Grab, Singtel, Sea Ltd and Ant Group. These businesses were assessed based on their value proposition, use of technology to improve financial inclusion and growth prospects. In this example, MAS has clearly adapted to changing trends and discarded notions of financial services only belonging to financial institutions. By assimilating these non-banks into their supervision umbrella, MAS also ensures that these new firms are subject to the same regulations as other banks, ensuring a level playing field in terms of scrutiny and compliance to rules.

## Over-regulation?

The rate of adoption of Fintech and the potential for players to scale rapidly has also put pressure on regulators to prevent concentration and systematic risk. However, regulators may not necessarily have the full picture or may lack reliable information on the ground about the structure and operations of Fintech firms and their markets, imposing stringent rules that curb financial innovation instead of encouraging them.

For example, regulators in China introduced several measures aimed at fintech firms to curb perceived monopolistic behavior, risky lending practices and lack of protection for customer data.

As a result, fintech giant, Ant Group has been directed to restructure itself into a financial holding company where all its subsidiaries engaged in financial activities must be subjected to financial regulations under the PBOC. This will also require them to have paid-in capital of at least 50% of the total registered capital of all the financial institutions they own. The stricter capital requirements are expected to constraint Ant’s huge loans business \[4\].

Ant Group has also been directed to remove its financial products Huabei and Jiebei from the Alipay platform and delinking them from the Alipay payments infrastructure. The delinking of Ant's consumer credit and microloan business is expected to further weaken its value proposition of providing competitive financial services through its Alipay platform. Controls on minimum deposit amounts and limits on the investments allowed for users in Yu'e Bao, Ant’s money-market fund platform, has also pushed investors to move their funds away from the Alipay platform.

The recent regulation changes in China are expected to significantly increase compliance costs for fintech companies and lead to moderate fintech growth and investment in the sector. It is well worth noting that regulators in China have evolved from adopting a lenient and light-handed approach to a stricter and more stringent regime. However it is not surprising given its unfortunate experience with P2P lenders where lenient, wait-and-see approaches led to unsustainable growth, massive fraud and subsequent crash of the industry with unfortunate consequences to millions of retail customers\[5\].

**In conclusion**, the rapid pace of change and innovation have required regulators to be agile and adaptive to changing trends. Regulators have also had to balance supporting Fintech and disruptive technologies while also mitigating risks to financial integrity and stability. While some regulators have adopted a one-size-fits-all approach to regulate these firms, many more have adopted new frameworks and guidelines to regulate fintech firms both as a whole and individually. Regulators have also had to look outwards in their approaches by increasing collaboration internationally. They have also had to re-think their use of technology and re-design themselves to become more progressive in their approach of regulation.

## References

\[1\] Overview of Regulatory Sandbox. (n.d.). Retrieved September 27, 2022, from <https://www.mas.gov.sg/development/fintech/regulatory-sandbox>

\[2\] World Bank and Cambridge Center for Alternative Finance. (2019) “Regulating Alternative Finance: Results from a Global Regulator Survey”. 2019 <https://openknowledge.worldbank.org/handle/10986/32592>

\[3\] MAS Announces Successful Applicants of Licences to Operate New Digital Banks in Singapore. (n.d.). Retrieved September 30, 2022, from <https://www.mas.gov.sg/news/media-releases/2020/mas-announces-successful-applicants-of-licences-to-operate-new-digital-banks-in-singapore>

\[4\] Writer, S. (2021, March 3). Ant Group thrown into disarray by China’s new financial rules. Nikkei Asia. Retrieved September 29, 2022, from <https://asia.nikkei.com/Business/Finance/Ant-Group-thrown-into-disarray-by-China-s-new-financial-rules2>

\[5\] PYMNTS. Protests Mark China’s Ruptured P2P Lending Landscape. August, 2018. <https://www.pymnts.com/news/international/2018/china-protestors-p2p-lending-regulationfraud-debt/>

World Bank. (2020). How regulators respond to Fintech: Evaluating the different approaches–sandboxes and beyond. World Bank. <https://openknowledge.worldbank.org/handle/10986/33698>

de Koker, Morris, N., & Jaffer, S. (2019). Regulating financial services in an era of technological disruption. Law in Context (Bundoora, Vic.), 36(2), 90–112. <https://doi.org/10.26826/law-in-context.v36i2.98>

Fintech : The Experience so Far - Executive Summary (English). Washington, D.C. : World Bank Group. <http://documents.worldbank.org/curated/en/130201561082549144/Fintech-The-Experience-so-Far-Executive-Summary>
