---
title: "Banks have changed the way they deploy technology"
author: "Imran Ibrahim"
date: August 24, 2024
date-modified: "last-modified"
toc: true
execute: 
  eval: true
  echo: true
  freeze: true
  warning: false
  message: false
---

# Assignment Topic

In 2018, the CEO of DBS Piyush Gupta has said that At DBS, we act less like a bank and more like a tech company and this sufficiently reflects how banks have changed the way they view and use technology.

Appraise and explain banks have changed the way they deploy technology in their banking business.

## Introduction

After the Global Financial crisis of 2008, as banks were grappling with the fallout from the crisis and new regulation regimes, they were occupied with changing their risk policies, re-thinking exposure to markets and increasing their capital adequacy requirements. At the same time, Fintech firms and other Tech fins, who were not subjected to the same levels of pressure from regulators and governments, came forward to expand their suite of services, meeting an increasing demand from a customer base seeking a new suite of digital and customized services.

Fintech firms had the advantage of complementary technologies, talent with knowledge of banking and their businesses, freedom from legacy IT systems, a focused product line and an existing customer base already entrenched in their ecosystems.

For example, it was said \[1\] that a key impetus for DBS’s digital transformation was the increasing competition from fintech firms in the region. Alibaba had expanded aggressively in Southeast Asia through its controlling stake in e-commerce player Lazada. Alibaba’s Ant Financial then merged Lazada’s payments system with its flagship Alipay wallet. Similarly, Grab also introduced Grab Pay, a mobile e-wallet that could be linked to customers’ credit and debit cards, along with other financial services such as loans and insurance offered in its wholly digital proposition.

In traditional banks, technology had only been used to address the operational, reliability and security aspects of banking services. In comparison, fintech firms brought with them the use of disruptive technologies consisting of cloud computing, artificial intelligence, machine learning, big data, blockchain etc to bring about new novel solutions and ways to service customers. With the entrants of new non-bank entities providing basic financial services and utilizing technology to entice customers, banks like DBS began to think more seriously about how to compete and how to deploy technology in their banking business.

## Reduction in Physical touch points

In 2017, DBS introduced the first Video Teller Machines (VTMs)\[2\] across Singapore. These teller machines provide 24 hour banking services to customers, with the option of interacting with bank officers through live video streaming. The combination of redesigning the function and utility of an ATM to include more self-serve functions, as well as the ability of having ‘face to face’ help through live video enabled the bank to present a new way of delivering services in physical branches. This improved customer experience and helped reduce waiting times in branches.   

Similarly, in 2018, OCBC announced that half of its bank tellers would be redeployed to other roles with the introduction of new ATMs and digital service kiosks in branches \[3\]. These new machines took 2 years to design and incorporated 15 of the most frequent counter services, effectively functioning as mini bank branches. The new machines also include new capabilities like biometric authentication and signature pads for signed transactions. OCBC estimates that these new machines would save customers an average of 15 mins compared to previous.

In comparison to fintech firms which offer solely online, digital, and cashless services; banks like DBS and OCBC recognize that they are unable to repackage their legacy services to compete with these digital offerings. However, using technology, they could improve the delivery of existing services and in the process, improve customer journeys and experiences, keeping them happy and satisfied.

## Agile Operations

Unencumbered by legacy IT systems that serve multiple businesses and product lines, fintech firms which offered a smaller suite of services were able to leverage on their existing technologies to lower cost of entry, increase speed to market, and directly pass on benefits to customers in the form of lower priced services and products. On the other hand, traditional banks were managing multiple IT systems, most of which were not interoperable with each other, supporting needs for multiple business units and product lines.

In the case of DBS, they made the decision to convert their core IT systems to a component-based infrastructure by means of scalable cloud-based deployment. Legacy banking applications and systems were gradually moved into modern hardware or implemented to the cloud, empowering the delivery of efficient and scalable solutions.

Cloud computing can be defined as the on-demand delivery of IT resources, especially computing power, and data storage, through a cloud services platform via the internet. As they decommissioned servers and began to shrink data centres, DBS instituted a policy of “everything goes cloud” \[1\]. Its IT systems changed from being cloud-ready to cloud-optimized and, eventually, to cloud-native. DBS also partnered with Amazon Web Services (AWS) to develop competence in cloud engineering.

When developing new applications, DBS had focused on usability and re-usability. Hence, they made a conscious decision to develop applications which could function in the cloud, work as micro-services, and be API-ready. This ensured that they did not invest in technologies that were not scalable and flexible for future disruptions. This also accorded speed, flexibility, and experimentation when developing new digital solutions.

Similarly, for managing customer data, multiple Customer Relationship Management (CRM) systems were revamped, and data lakes implemented. Data lakes provide a single place where data can be collected across the company and be effectively analysed. This served to instil some level of interoperability between legacy systems, with the ability to draw insightful data points for the same customer. Previously, different business units had collaborated by means of bulk csv files or Manage Information systems (MIS); bankers could now leverage on real time updates directly uploaded to their respective CRM systems to gain more information on customer activities and transactions. This has enabled better data analytics of customer behaviour and preferences, improving cross-sell and ability to deliver more customised solutions.

## Invisible Banking

DBS CEO Piyush Gupta \[4\] describes invisible banking as “hiding banking services inside whatever it is that the customer really wants to do with his or her life, so that we can serve the customer at their convenience, in their domain, and on their time”.  Invisible banking enables customers to make financial transactions and decisions without consciously associating it as something separate from their other daily tasks. Banking services are delivered seamlessly such that it becomes embedded in their everyday activities. For example, paying your bills or sending a funds transfer should be as simple as sending a message to a friend or uploading a post to social media.

In the case of banks like DBS and OCBC, this starts from removing physical touchpoints, improving current frictions and manual processes, and delivering services in ways and medium that users can conveniently incorporate into their daily lives. For many banks, this is consistently embodied in the form of their mobile banking applications.

In 2016, DBS launched its rebranded and redesigned mobile banking application, Digibank \[5\] which delivered a significant number of self-service options and improvements over previous versions. Customers could open accounts through the app without the need to visit a branch, and other industry firsts were also introduced, which include:

1\) Viewing account balances with a single swipe on their mobile devices or Apple Watch without logging in

2\) Customising profiles and creating shortcuts for frequently used services

3\) Using a list of recent and favourite payees for faster transactions

4\) Using existing smartphone biometrics (eg Touch ID) to do faster log-ins

Often described as a ‘super-app’ for banking services, Digibank allows customers to perform basic banking, apply for new accounts and cards, trade stocks, invest, convert currencies, send overseas remittances, analyse net worth, plan for retirement, and even track their carbon footprint; providing integrated and instantaneous services by means of a single application and touchpoint \[6\].

It is worth noting that newer functions like Net Asset Value planner, leverages on AI and data analytics to provide useful insights for customers to track their wealth accumulation journey, empowering them to make better decisions to meet their retirement goals. Through predictively analysis, the app also provides useful insights on investment strategies and suggests investments aligned to customer risk profiles. 

The success of DigiBank has allowed DBS to launch a fully digital and branch-less service in India (2016) \[7\] and Indonesia (2017) \[8\]; where customer service is powered by a 24-hour AI-driven virtual assistant. Making use of Natural Language Processing, the virtual assistant is able to understand customer questions and respond real-time to urgent enquiries. With seamless non face to face onboarding, clients are also able to open their accounts faster and more conveniently. It is not surprising then that DBS shares the same advantage as online fintech firms in these countries and are able to provide clients with lower cost fees and competitive interest rates due to the benefits derived from technologies utilized.

**In conclusion**, banks like DBS exemplify how banks globally are using technology to stay competitive and penetrate new markets. Rather than inventing new novel solutions, they are concentrating on removing frictions, improving pain points and manual processes, revamping legacy systems and investing in new scalable technologies to make their services more accessible and to improve user experiences and journeys.

DBS CFO Chng Sok Hui \[9\] mentioned that digital segment customers had a cost-to-income ratio of 34% Versus traditional segment clients of 54%. It is not surprising then, why banks like DBS have changed the way they deploy technology to stay relevant and competitive.

## References

\[1\] Sia, Weill, P., & Zhang, N. (2021). Designing a Future-Ready Enterprise: The Digital Transformation of DBS Bank. California Management Review, 63(3), 35–57. <https://doi.org/10.1177/0008125621992583>

\[2\] DBS/POSB launches Singapore’s first video teller machines across nine locations. (n.d.). Retrieved September 28, 2022, from <https://www.dbs.com/newsroom/DBS_POSB_launches_Singapores_first_video_teller_machines_across_nine_locations>

\[3\] Ming, T. E. (2018, July 23). OCBC to cut half of bank teller jobs in next two years; affected staff to be reassigned. TODAY. Retrieved September 28, 2022, from <https://www.todayonline.com/singapore/ocbc-cut-half-bank-teller-jobs-next-two-years-affected-staff-be-reassigned>

\[4\] What will (and won’t) change in the future of Asia: An interview with the CEO of DBS. (2020, September 29). McKinsey & Company. Retrieved September 28, 2022, from <https://www.mckinsey.com/featured-insights/asia-pacific/what-will-and-wont-change-in-the-future-of-asia-an-interview-with-the-ceo-of-dbs>

\[5\] DBS breaks new ground in digital banking. (n.d.). Retrieved September 28, 2022, from <https://www.dbs.com/NewsPrinter.page?newsId=jy1w61p0&locale=en>

\[6\] Services available on digibank \| DBS Singapore. (n.d.). Retrieved September 28, 2022, from <https://www.dbs.com.sg/personal/deposits/bank-with-ease/manage-account-and-more.page>

\[7\] DBS launches India’s first mobile-only bank, heralds ‘WhatsApp moment in banking.’ (n.d.). Retrieved September 28, 2022, from <https://www.dbs.com/newsroom/DBS_launches_Indias_first_mobile_only_bank_heralds_WhatsApp_moment_in_banking>

\[8\] DBS launches digibank, an entire bank in the phone, in Indonesia. (n.d.). Retrieved September 28, 2022, from <https://www.dbs.com/newsroom/DBS_launches_digibank_an_entire_bank_in_the_phone_in_Indonesia>

\[9\] Becoming more than a bank: Digital transformation at DBS. (n.d.). McKinsey & Company. Retrieved September 28, 2022, from <https://www.mckinsey.com/industries/financial-services/our-insights/banking-matters/becoming-more-than-a-bank-digital-transformation-at-dbs>
